### ISSUE TITLE
给你个👍 背景、字体颜色需要调整下

### ISSUE THREAD

**Issue by tanwenhai** [kookob/mybatis-log-plugin#1]
![image](https://user-images.githubusercontent.com/6077165/31528109-19139da2-b004-11e7-8e9b-f3fee7f966c3.png)

## 这个log能插入到run/debug窗口中吗

**Comment by kookob** [comment]
理论上是可以的，但是考虑到run/debug日志太多，不好定位，所以独立一个窗口出来。
你上面黄色的背景色是你自己设置的吧？(猜测你装的其他插件关键词触发的)
我只对右键恢复sql做了个背景色，而且也不是黄色的。

**Comment by kookob** [comment]
@tanwenhai 你好，可以看下最新的Issues，之前没想到你的这个问题是不同主题引起的，刚更新了个版本，请关注下。
