### ISSUE TITLE
插件不起作用

### ISSUE THREAD

**Issue by ZaneZ2** [kookob/mybatis-log-plugin#10]
![Mybatis sql log如图](https://user-images.githubusercontent.com/18257520/41268394-6b63c91e-6e32-11e8-8a3c-fd28cca43756.png)

没有将“?”进行恢复

![log 日志](https://user-images.githubusercontent.com/18257520/41268450-ac3927cc-6e32-11e8-82b2-eda1857022cf.png)

sql打印log已包含"Preparing:"和"Parameters:"
按照动图示例，选中console的sql日志，右击 "Restore Sql from Selection"还是不能还原

![Restore Sql from Selection进行还原](https://user-images.githubusercontent.com/18257520/41268693-f83252ec-6e33-11e8-982f-b4970f417716.png)

**Comment by kookob** [comment]
@Bored-AnnoYing 本地测试没有重现，告知下版本号，最新2.0.4，如果不是最新，更新下版本再试。

**Comment by ZaneZ2** [comment]
![Mybatis log plugin version](https://user-images.githubusercontent.com/18257520/41325301-16a814d8-6eec-11e8-898f-fbdc800b5374.png)

插件版本号是最新的2.0.4，ieda版本是2018.1.4

**Comment by kookob** [comment]
@Bored-AnnoYing 其他语句会出现这问题吗？不确定是不是2018.1.4的问题，我2017重现不了。
或者你把上面还原的语句粘贴到这边我再试下你的原始log。

**Comment by ZaneZ2** [comment]
```log
[DEBUG] [2018-06-13 10:44:24.300] [http-nio-9050-exec-2] com.hollysys.hollipark.imrs.dao.mapper.MeterMapper.selectMeterNo debug (line: 159)
 ==>  Preparing: SELECT meter_no FROM t_imrs_meter WHERE (meter_type = ? AND user_flag='1') 

[DEBUG] [2018-06-13 10:44:24.300] [http-nio-9050-exec-2] com.hollysys.hollipark.imrs.dao.mapper.MeterMapper.selectMeterNo debug (line: 159)
 ==> Parameters: 1(Integer)
```

**Comment by kookob** [comment]
@Bored-AnnoYing 可以重现了，中间的换行引起。
2.0.5会修复，目前为了兼容各种各样的输出，很多格式考虑不全。
版本可能没这么快发布，提交，审核，耗时较久，影响不大的问题，可能没那么快更新上去。

**Comment by ZaneZ2** [comment]
好的，谢谢你，希望下个版本可以更新 :smile:
