### ISSUE TITLE
我买了你插件花了4美元，激活不了啊

### ISSUE THREAD

**Issue by flycatzly** [kookob/mybatis-log-plugin#104]
他一直提示：Key is invalid. Help  
![image](https://user-images.githubusercontent.com/15058066/88020782-e5bdb180-cb5e-11ea-8066-8a827f4df86a.png)  怎么回事啊，白买了激活不了

**Comment by kookob** [comment]
你好，请用邮箱跟我联系哦！

**Comment by flycatzly** [comment]
> 你好，请用邮箱跟我联系哦！

我怎么知道你邮箱呢

**Comment by kookob** [comment]
插件说明那边有：kookob@gmail.com

**Comment by flycatzly** [comment]
> 插件说明那边有：[kookob@gmail.com](mailto:kookob@gmail.com)

问题已经描述了，能看一下嘛，如果不能解决，可以不可以退款

**Comment by kookob** [comment]
邮箱沟通，这边不再讨论
