### ISSUE TITLE
不支持最新版的idea，日志打印不出来，花钱买了一年结果才用了没多久

### ISSUE THREAD

**Issue by yinqichao** [kookob/mybatis-log-plugin#108]

**Comment by kookob** [comment]
idea和插件分别哪个版本，我检查一下？

**Comment by yinqichao** [comment]
插件版本是：2020.7.2
idea 版本是：

IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Licensed to ** *
You have a perpetual fallback license for this version
Subscription is active until June 26, 2021
Runtime version: 11.0.7+10-b765.65 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: Statistic, Lombook Plugin, MyBatisLog, SequenceDiagram, com.alibaba.p3c.smartfox, mobi.hsz.idea.gitignore, cn.wuzhizhan.plugin.mybatis, cn.yiiguxing.plugin.translate, com.ccnode.codegenerator.MyBatisCodeHelperPro

---以上复制于About---

**Comment by kookob** [comment]
@yinqichao 插件应该没有报错吧？日子打印不出来，要检查下settings里面的设置和日志的输出格式

**Comment by yinqichao** [comment]
插件没有报错，之前前几个版本的idea还是能正常打印和使用的，settings里的配置也没动过，后来更新到最新的idea后，日志就打印不了了

**Comment by kookob** [comment]
麻烦你用下面代码运行一下，看下结果：
注意窗口旁边的run按钮是要启动的哦。
如果还是没有输出，试下右键的`Restore Sql`功能是否正常。

```java
public class MyBatisLogTest {
    public static void main(String[] args) {
        System.out.println("MyBatis Log Test: DEBUG sql1 -  ==>  Preparing: select * from t_table where name = ? and age = ?");
        System.out.println("MyBatis Log Test: DEBUG sql1 -  ==> Parameters: hello(String), 30(Integer)");

        System.out.println("MyBatis Log Test: INFO sql2 -  ==>  Preparing: update t_table set name = ? where id = ?");
        System.out.println("MyBatis Log Test: INFO sql2 -  ==> Parameters: world(String), 123(Integer)");

        System.out.println("MyBatis Log Test: WARN sql3 -  ==>  Preparing: delete from t_table where id = ?");
        System.out.println("MyBatis Log Test: WARN sql3 -  ==> Parameters: 123(Integer)");
    }
}
```

**Comment by yinqichao** [comment]
--  1  MyBatis Log Test: DEBUG sql1 -  ==>
 select *
 FROM t_table
 WHERE name = 'hello' and age = 30;
--  ------------------------------------------------------------------------------------------------
--  2  MyBatis Log Test: INFO sql2 -  ==>
 update t_table set name = 'world'
 WHERE id = 123;
--  ------------------------------------------------------------------------------------------------
--  3  MyBatis Log Test: WARN sql3 -  ==>
 delete
 FROM t_table
 WHERE id = 123;
--  ------------------------------------------------------------------------------------------------

确实是有打印出日志

我看了下你是对控制台里的文本做了解析和内容替换来实现日志的打印的对吧

那我到时再看看吧，检查下控制台的打印日志

**Comment by kookob** [comment]
是的，有些用log4j,logback有自己配置一些输出格式，要注意检查格式后面的空格或特殊字符。
