### ISSUE TITLE
下载地址无法使用

### ISSUE THREAD

**Issue by dyf2015** [kookob/mybatis-log-plugin#11]
如题

**Comment by dyf2015** [comment]
https://plugins.jetbrains.com/plugin/10065-mybatis-log-plugin

**Comment by dyf2015** [comment]
idea也无法拉取

**Comment by kookob** [comment]
@dyf2015 下面有个download:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=46399
idea有时候需要翻..
