### ISSUE TITLE
更新后没有许可

### ISSUE THREAD

**Issue by CZDouble** [kookob/mybatis-log-plugin#110]
不久前买的，更新了2020.1.3之后就不能用了，没有许可，非正版用户，需要重新购买？

**Comment by kookob** [comment]
用购买的邮箱给我发下邮件:
https://plugins.jetbrains.com/organization/abc

**Comment by CZDouble** [comment]
这个是我购买的邮箱😊


| |
Chen
|
|
15148376370@163.com
|
签名由网易邮箱大师定制
在2020年8月24日 15:36，ob<notifications@github.com> 写道：

用购买的邮箱给我发下邮件:
https://plugins.jetbrains.com/organization/abc
