### ISSUE TITLE
生成的sql日志中，未对字符串中的特殊字符进行转义，例如单引号等，造成sql无法执行问题

### ISSUE THREAD

**Issue by qiangbro** [kookob/mybatis-log-plugin#111]
如图：![image](https://user-images.githubusercontent.com/4646469/91409802-88f99900-e878-11ea-80bd-15fbbfbe45d1.png)

**Comment by kookob** [comment]
能否帮忙提供下原始语句？ 敏感表名啥的可以替换一下。

**Comment by qiangbro** [comment]
Mapper:
```java
@Select("select * from ibmp_example where instr(name, #{keyword})")
List<Document> findExamples(@Param("keyword") String keyword);
```
控制台log:
```txt
==>  Preparing: select * from ibmp_example where instr(name, ?) 
==> Parameters: angry'(String)
<==      Total: 0
```
sql log:
![image](https://user-images.githubusercontent.com/4646469/91412786-d972f580-e87c-11ea-87a3-bfe0bf143073.png)

**Comment by kookob** [comment]
收到，过后我考虑下，多谢。

**Comment by kookob** [comment]
@qiangbro 新版本已修复。
