### ISSUE TITLE
idea 2020.2.3 不兼容

### ISSUE THREAD

**Issue by LXC-9349** [kookob/mybatis-log-plugin#113]
不兼容(直到第193版。快照<IU-202.7660.26)
![image](https://user-images.githubusercontent.com/46589121/96824422-5aa3ce80-1461-11eb-9c44-9b2679a45816.png)

**Comment by kookob** [comment]
@LXC-9349 你好，旧版本已经不再维护了哦，可以试下新版本插件：
https://plugins.jetbrains.com/plugin/13905-mybatis-log-plugin
