### ISSUE TITLE
在接口上添加跳转到mapper的按钮

### ISSUE THREAD

**Issue by c332030** [kookob/mybatis-log-plugin#114]
作者你好，能不能在接口上加上对mapper的跳转，dao 层如果有继承的话，这个dao可能没有方法，也就没有跳转的地方
就像 Free Mybatis plugin 一样的
![image](https://user-images.githubusercontent.com/15310784/99207786-d04d5100-27f9-11eb-85cc-5d63b72d2b6a.png)

![image](https://user-images.githubusercontent.com/15310784/99207285-86b03680-27f8-11eb-94cc-018ecc0e3ed3.png)

**Comment by kookob** [comment]
是想要跳转到对应的mapper.xml文件吗？不跳转具体方法。
如果是这个需求，后续版本可以考虑加上。

**Comment by c332030** [comment]
> 是想要跳转到对应的mapper.xml文件吗？不跳转具体方法。
> 如果是这个需求，后续版本可以考虑加上。

是的
