### ISSUE TITLE
重复打印sql，mapper转向dao没有精确匹配

### ISSUE THREAD

**Issue by c332030** [kookob/mybatis-log-plugin#116]
我又来了

这是控制台里的最上面的日志时间
![image](https://user-images.githubusercontent.com/15310784/100833838-b96b5780-34a5-11eb-885e-e9ab896bc5d3.png)

这是匹配的sql，那个时间是小于控制台最小时间的，然后sql重复打印了
![image](https://user-images.githubusercontent.com/15310784/100833885-cbe59100-34a5-11eb-8778-dd82e80d8f6f.png)

mapperd转向dao时，匹配了多个
![Snipaste_2020-12-02_13-58-42](https://user-images.githubusercontent.com/15310784/100834253-8aa1b100-34a6-11eb-8fad-c0df296bbb07.jpg)

**Comment by kookob** [comment]
1.重复的问题是Junit测试还是正常启动的？你现在有升级2020.12.1的版本了吗？
2. mapper转向多个dao，如果检测不到唯一匹配的话，是会列出多个给用户选，这个应该还好吧？

**Comment by c332030** [comment]
> 1.重复的问题是Junit测试还是正常启动的？你现在有升级2020.12.1的版本了吗？
> 2. mapper转向多个dao，如果检测不到唯一匹配的话，是会列出多个给用户选，这个应该还好吧？

jrebel正常启动的，第二个问题不是必现的

**Comment by kookob** [comment]
重复的问题，试下最新版本？
跳转功能，我能测试场景不太多，可能不好排查，如果你能帮忙提供个重现的代码就非常好了。

**Comment by c332030** [comment]
我试下

**Comment by c332030** [comment]
最新版两个都好了
