### ISSUE TITLE
可以麻烦添加IDEA2020版本的兼容吗

### ISSUE THREAD

**Issue by blankhang** [kookob/mybatis-log-plugin#117]

**Comment by kookob** [comment]
@blankhang 
你好，2020以上版本，有收费版本，你可以考虑下：
https://plugins.jetbrains.com/plugin/13905-mybatis-log-plugin
如果不太愿意付费，可以再回复找我拿优惠码

**Comment by blankhang** [comment]
求给个优惠码

ob <notifications@github.com> 于2020年12月3日周四 上午11:48写道：

**Comment by kookob** [comment]
MDRN4-PHN7K-HPC87-4XZUE-WXAMR
下单的时候，折扣码那边填上。
