### ISSUE TITLE
Mybatis Log Plugin License Authorization Failed.

### ISSUE THREAD

**Issue by PetalQ** [kookob/mybatis-log-plugin#121]
正版idea，2021.1.3
插件是2021.5.1
帮助-注册里，显示已经正常授权，但是无法使用。
![image](https://user-images.githubusercontent.com/28222123/127095233-0d73d06c-c16c-42a4-8e07-1ba75e8602ee.png)
![image](https://user-images.githubusercontent.com/28222123/127095260-9d82935a-ad43-4ca9-8d43-9146ca2e84d4.png)
![image](https://user-images.githubusercontent.com/28222123/127095277-83fa053b-ceb2-42a3-ba7f-a4ae36c60bc5.png)

**Comment by kookob** [comment]
IDE是否有重启一下？

**Comment by PetalQ** [comment]
> IDE是否有重启一下？

重启IDE、PC都不生效。 @kookob

**Comment by kookob** [comment]
IDE正版，显示有效，是公司内部授权服务器激活的方式吗？还是什么场景？正常应该有个有效期？可能跟这个有关系。
![image](https://user-images.githubusercontent.com/3116606/127105443-648b1c1f-8c6c-49d4-af1d-50ce400c6c85.png)

**Comment by PetalQ** [comment]
IDE的授权是统一通过许可证服务器授权的，不是单独的个人license。 @kookob 
这个情况需要出新版本吗？

**Comment by kookob** [comment]
这种情况可能需要使用本地授权版本，你下载安装一下，然后把购买的邮箱发我一下。
https://www.yuque.com/kookob/plugin/local

**Comment by PetalQ** [comment]
> 这种情况可能需要使用本地授权版本，你下载安装一下，然后把购买的邮箱发我一下。
> https://www.yuque.com/kookob/plugin/local

公司内网访问不了下载地址obroom这个网站，被归类为色情网站给拦了。。。如果方便的话，可以帮忙发下邮箱，我验证下，***@qq.com，购买的邮箱也是这个号。

**Comment by kookob** [comment]
已发送邮箱

**Comment by PetalQ** [comment]
> 已发送邮箱

已经可以了，多谢。
