### ISSUE TITLE
sql不打印

### ISSUE THREAD

**Issue by RuoBingCoder** [kookob/mybatis-log-plugin#122]
spring boot在yaml已经配置了log level ,但是控制台不打印sql；

idea 版本 2021.2 

![image](https://user-images.githubusercontent.com/29751035/127596506-3c5e3ea7-41ab-4f03-bdfb-38f64a974f17.png)

**Comment by kookob** [comment]
照着这个文档排查下：
https://www.yuque.com/kookob/plugin/mybatis-log-faq
