### ISSUE TITLE
插件不能使用

### ISSUE THREAD

**Issue by tenyears94** [kookob/mybatis-log-plugin#123]
本月续费后插件不能使用了，邮箱742423357@qq.com

**Comment by kookob** [comment]
是哪种方式续费的？官网的话，试下用激活码激活。

**Comment by tenyears94** [comment]
`MyBatis Log plugin is not enabled.
Click the Rerun button on the left to enable it.`
老是提醒这个，我点了 Rerun也没用

**Comment by kookob** [comment]
装的是哪种版本？仓库的还是本地授权的？过期了吗？

**Comment by tenyears94** [comment]
![image](https://user-images.githubusercontent.com/49542458/170421425-ab84bd53-1c93-4392-bdc7-74b1bc203b9b.png)
![image](https://user-images.githubusercontent.com/49542458/170421507-04aa3dec-c073-435f-a705-4593c464ff18.png)
没有过期，版本：2022.5.1

**Comment by kookob** [comment]
要不试下卸载重装？

**Comment by tenyears94** [comment]
试了三次，还是不行

**Comment by kookob** [comment]
我用邮件联系您
