### ISSUE TITLE
2022.1.3idea 无法使用

### ISSUE THREAD

**Issue by rrge** [kookob/mybatis-log-plugin#124]
安装最新版后，打开项目提示MyBatis Log plugin incompatible with this version, Please upgrade the plugin.

**Comment by kookob** [comment]
装的是哪个版本，你这个应该装2022.7.3，试着重启下。
https://plugins.jetbrains.com/plugin/13905-mybatis-log/versions

**Comment by rrge** [comment]
IDEA商店目前最新版的是2022.5.1版本的

**Comment by kookob** [comment]
仓库好像没同步最新版本出来，你直接用上面地址下载更新看下？

**Comment by rrge** [comment]
Plugin 'MyBatis Log' (version '2022.7.3') is not compatible with the current version of the IDE, because it requires build 222.1 or newer but the current build is IU-221.5921.22

**Comment by kookob** [comment]
抱歉，可能有点问题，IDE需要升到222.1，需要等发布个修复版本，或你升级下IDE

**Comment by rrge** [comment]
IDE目前最新稳定版就是2022.1.3

**Comment by ki827** [comment]
IntelliJ IDEA 2022.1.3 (Ultimate Edition) 应该使用哪个版本？目前补丁商店无法检索出来

**Comment by kookob** [comment]
@Rainyun @qinrongjun 最新兼容版本已提交仓库审核，预计2个工作日内通过，抱歉给你们造成的不便。

**Comment by rrge** [comment]
好的，感谢作者

**Comment by kookob** [comment]
@Rainyun 已经审核通过，请根据IDE版本下载相应插件，谢谢支持！

**Comment by kookob** [comment]
@Rainyun 已经审核通过，请根据IDE版本下载相应插件，谢谢支持！
