### ISSUE TITLE
IntelliJ IDEA 2022.1.3不能使用

### ISSUE THREAD

**Issue by wenkesong-li** [kookob/mybatis-log-plugin#125]
才购买的 用了几天提示不能用了
要怎么解决

**Comment by kookob** [comment]
IDE哪个版本的，急用的话，我先发给你，目前更新版本在审核中，预计两天内通过。

**Comment by kookob** [comment]
@wenkesong-li 已经审核通过，请根据IDE版本下载相应插件，谢谢支持！
