### ISSUE TITLE
无法使用 Nothing to show

### ISSUE THREAD

**Issue by RoeGross** [kookob/mybatis-log-plugin#126]
无法使用 Nothing to show

**Comment by RoeGross** [comment]
![图片](https://user-images.githubusercontent.com/42738826/178218877-3c82ea08-f197-43b9-bce7-8d216e1f83a0.png)

**Comment by RoeGross** [comment]
![图片](https://user-images.githubusercontent.com/42738826/178218942-6fba0d9a-fbef-4658-b968-77b100d04d8f.png)

**Comment by kookob** [comment]
插件用的哪个版本？试试7.6的是否正常：
https://plugins.jetbrains.com/plugin/13905-mybatis-log/versions/stable/191708

**Comment by kookob** [comment]
有重启过吗？有个7.8兼容的版本还没审核通过。

**Comment by RoeGross** [comment]
重启过了，2022.7.6版本的.

**Comment by RoeGross** [comment]
2022.5.2版本没问题

**Comment by kookob** [comment]
好的，那5.2先用，等7.8审核通过的时候再试下有没有兼容，因为改用的SDK版本差异太大，各个IDE版本都不太一样，可能有些漏了
