### ISSUE TITLE
IDEA 2022.2 无法从dao跳转到mapper.xml，可以打印出完整sql

### ISSUE THREAD

**Issue by watilion** [kookob/mybatis-log-plugin#127]

**Comment by kookob** [comment]
Settings里面配置有开启吗？是左边有出现图标然后跳转不了，还是没图标？

**Comment by watilion** [comment]
settings里配置开启了，左边没有图标
![image](https://user-images.githubusercontent.com/19620174/182022425-6917f397-f451-4a81-92c0-ef9b2f18373c.png)

**Comment by watilion** [comment]
setting里关闭后清空idea的缓存后再重新打开，可以进行跳转了
