### ISSUE TITLE
购买后许可日期未延长

### ISSUE THREAD

**Issue by HeTun-code** [kookob/mybatis-log-plugin#128]
我购买了一个3年的许可，但是由于点了试用，现在显示许可在29天内到期

**Comment by kookob** [comment]
可以在试用界面，移除授权，重新用账号登录即可。

**Comment by HeTun-code** [comment]
试用界面在哪里打开呢 插件页面没有找到移除授权

**Comment by kookob** [comment]
Help->Register...->MyBatis Log Plugin->右边`Remove License`

**Comment by HeTun-code** [comment]
好了 解决了~ 谢谢
