### ISSUE TITLE
插件不可用

### ISSUE THREAD

**Issue by miaoxiepro** [kookob/mybatis-log-plugin#129]
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/20608661/208806486-cc978065-63f2-41a2-ba47-80af8e812580.png">

官网购买,激活码注册.
插件重装,可以正常激活使用,当idea重启后就提示授权失败
邮箱 978215550@qq.com

**Comment by kookob** [comment]
IDE是什么版本？你先试着Tab激活其他插件，比如Terminal，不要默认激活MyBatis Log，然后再重启下IDE看下。
（不是授权激活那里，是IDE主界面最下面的tab栏）

**Comment by miaoxiepro** [comment]
最新版本,2022.3.1

**Comment by kookob** [comment]
试了吗？

**Comment by miaoxiepro** [comment]
如果选择别的tab窗口,比如build, 关闭ide重启后,mybatis log的tab窗口也是正常的.这个是BUG吧~

**Comment by miaoxiepro** [comment]
如果是IDE正常关闭,重启启动IDE后插件正常运行,如果使用command+q强制关闭IDE,mybatis log插件就会提示授权失败

**Comment by kookob** [comment]
对，这个是新版IDE在初始化完成前获取授权信息返回null的一个错误，需要下个版本去做个兼容处理。

**Comment by miaoxiepro** [comment]
ok 那就没问题了,希望尽快更新~
