### ISSUE TITLE
多线程打印SQL异常

### ISSUE THREAD

**Issue by mate99** [kookob/mybatis-log-plugin#13]
多个线程输出mybatis日志时，SQL语句错位。
日志输出顺序：
 thread1： Preparing 
 thread2： Preparing
 thread1： Parameters
 thread2： Parameters

**Comment by kookob** [comment]
@mate99 日志解析是根据控制台的输出来处理的，如果控制台是这样输出，暂时就没解了，你可以手工复制需要解析的SQL到某个文件，然后右键Restore sql from selection应急。
