### ISSUE TITLE
为什么日志格式多个空格, 插件就无法输出SQL!!!

### ISSUE THREAD

**Issue by zhihaoHappyeveryday** [kookob/mybatis-log-plugin#132]
<pattern>[${springAppName}] %highlight([%5p]) %magenta(%d{yyyy-MM-dd HH:mm:ss SSS}) %green([%t])
                [%X{X-B3-TraceId:-}][%X{X-B3-SpanId:-}][%X{X-Span-Export:-}]- %cyan(%c) >>> %m %n</pattern>
                
                
   %m %n      得变成      %m%n
   
   问题是公司项目全部都是这样的,  得去修改,  之前用过其他插件好像没有这个问题

**Comment by kookob** [comment]
你在settings那边配置下Preparing和Parameters的空格看能不能解决，不行你把日志输出粘一下，我过后检查下场景。

**Comment by zhihaoHappyeveryday** [comment]
> settings
配置下Preparing和Parameters的空格 ,  好像会自动去空格无效果;

[x-ocs-api] [DEBUG] 2023-10-18 15:13:16 511 [http-nio-8088-exec-1]
                [bc9e50593f851a09][bc9e50593f851a09][true]- com.x.mapper.master.MasterStateMapper.selectByCondition >>> ==>  Preparing: SELECT master_state_id,master_id,register_time,settle_status,settled_date,rule_exam_status,blacklist_status,certify_status,certify_time,certify_amount,grade_id,grade_money,move_c_certify_status,move_c_certify_amount,free_certify_status,is_certify_equity,reentry_status,direct_master_status,rigorous_selection_status,master_belong_shops,city_hero_status,contract_master_status,restrict_action,rest_state,last_start_work_time,limit_lv1_goods_ids,create_time,update_time FROM master_state WHERE ( master_id in ( ? ) )  
                
                
[x-ocs-api] [DEBUG] 2023-10-18 15:13:16 512 [http-nio-8088-exec-1]
                [bc9e50593f851a09][bc9e50593f851a09][true]- com.x.mapper.master.MasterStateMapper.selectByCondition >>> ==> Parameters: 58996(Long) 
[x-ocs-api] [DEBUG] 2023-10-18 15:13:16 532 [http-nio-8088-exec-1]
                [bc9e50593f851a09][bc9e50593f851a09][true]- com.x.mapper.master.MasterStateMapper.selectByCondition >>> <==      Total: 1

**Comment by kookob** [comment]
收到，过后我验证下

**Comment by zhihaoHappyeveryday** [comment]
> 收到，过后我验证下

![image](https://github.com/kookob/mybatis-log-plugin/assets/49114216/2c7b32ba-4d10-4325-bce3-6b18ad852635)
去掉插件控制台才有日志输出,  恢复之前的就无法输出了

**Comment by kookob** [comment]
嗯，了解，这个是插件匹配格式要求的，我想想能不能兼容

**Comment by zhihaoHappyeveryday** [comment]
> 你在settings那边配置下Preparing和Parameters的空格看能不能解决，不行你把日志输出粘一下，我过后检查下场景。

好的,  感谢作者, 辛苦

**Comment by zhihaoHappyeveryday** [comment]
> 嗯，了解，这个是插件匹配格式要求的，我想想能不能兼容

大佬修复了麻烦回复下哈!

**Comment by kookob** [comment]
抱歉，没这么快啊，修复也得发新版，等审核，得几天以上。

**Comment by kookob** [comment]
@chenzhihao1040728129 新版本在审核中了。你可以先通过这个地址下载：
https://plugins.jetbrains.com/files/13905/421422/mybatis-log.jar
在settings里面有个结束标记符配置，你如果是上面`%m %n`中间有个空格的，你就配个空格上去就可以了。

**Comment by zhihaoHappyeveryday** [comment]
> @chenzhihao1040728129 新版本在审核中了。你可以先通过这个地址下载： https://plugins.jetbrains.com/files/13905/421422/mybatis-log.jar 在settings里面有个结束标记符配置，你如果是上面`%m %n`中间有个空格的，你就配个空格上去就可以了。

好的, 感谢作者!
