### ISSUE TITLE
更新到2018.2.5存在的一些问题

### ISSUE THREAD

**Issue by bfchengnuo** [kookob/mybatis-log-plugin#17]
大概作者已经发现这些小问题了，期待下一次更新

IDEA 版本：2018.2.5
插件版本：2.0.6

启用插件后在 `Run  Dashboard` 中输出的日志不能自动滚动（Scroll to the end 失效）

异常信息类名无高亮显示，不可点击跳转定位。

禁用插件后恢复正常。

**Comment by kookob** [comment]
@bfchengnuo 嗯，我有紧接着发了个2.0.7的版本，还没审核通过。
但是你上面提的那些：
Scroll to the end 这个你鼠标点完，要移开，这个是IDE自带的，插件不会影响到这功能。
异常信息类名无高亮显示，这个没明白是哪个问题？
目前跟某个插件有冲突，在2.0.7里面解决了，你这两天关注然后更新下，看还会不会存在。

**Comment by bfchengnuo** [comment]
@kookob 
关于 `Scroll to the end` 的问题：

![gif](https://user-images.githubusercontent.com/16206117/47286334-cfe52a80-d620-11e8-88a4-e904c2da0275.gif)

我点击激活 `Scroll to the end` 后，当有日志输出时，自动取消，禁用插件后可解决。

关于第二个问题，对照如下：
**启用插件：**

![1](https://user-images.githubusercontent.com/16206117/47286223-58af9680-d620-11e8-92b8-f9e931581a2e.png)

**禁用插件：**

![2](https://user-images.githubusercontent.com/16206117/47286252-7977ec00-d620-11e8-813c-5da4150f7a04.png)

**Comment by kookob** [comment]
你好，现在可以升级到2.0.7了，你升级试下。
不过升级的内容没有涉及到你上面的两个问题。
可以比较肯定的说，你上面的两个问题，不大可能是我这个插件引起的，intellij的console输出我那插件不会去影响的，至于你说禁用这插件后就恢复正常，我也是很懞。
我IDE版本跟你一样没出现上面情况。
尝试下其他解决方案：
1、插件卸载重装
2、Invalidate and Restart 看下
3、排查下是否还有其他插件导致的冲突
4、或者右下角有报错信息的话，麻烦提供下。

**Comment by bfchengnuo** [comment]
@kookob 
我升级了 2.0.7 版本，测试一切正常了，感谢更新。

PS：我也不清楚是不是插件的相互作用导致的，不过之前确实禁用后就没问题，开启100%复现，这次更新已解决了这个问题 ♪(^∇^*)
