### ISSUE TITLE
怎么随idea一起启动呢

### ISSUE THREAD

**Issue by TGich** [kookob/mybatis-log-plugin#19]
现在每次要手动去tools里点击才能在底部显示

**Comment by kookob** [comment]
@TGich 不好意思，目前不支持这个功能，也不打算加上。原因如下：
1、你不知道用户打开的项目是否需要用到mybatis，默认开启过滤，也会占用一部分性能。
2、如果是因为没有及时开启，导致部分sql没过滤出来，可以通过右键菜单选中解决的。
3、有个快捷键可以用ctrl+shift+alt+o。
所以想不出加这功能的好处在哪。
