### ISSUE TITLE
请问设置了filter之后可以清除里面的设置吗

### ISSUE THREAD

**Issue by yugijiudai** [kookob/mybatis-log-plugin#2]
设置了filter之后发现无法清除设置，那个filter框一定要填东西。
第一次选Restore Sql from Selection的时候那个背景颜色可以自己更换吗,那片黄色实在太刺眼了

**Comment by kookob** [comment]
@yugijiudai filter果然有bug，抽空我修复一下。
黄色背景，当时就是为了显眼，好定位，才弄的颜色，暂时没做成可配置。
这功能正常用的不多吧，如果加配置改动可能就多些，目前没什么人有需要这个配置，就不增加插件的复杂度了。
如果实在想改，建议你把代码clone下来，自己改下颜色，编译下。

**Comment by kookob** [comment]
@yugijiudai 后面我修复filter的bug时，顺便把颜色调温和一些。

**Comment by yugijiudai** [comment]
@kookob 嗯嗯,还有一个问题就是有些mybatis的版本他输出是Executing而不是Preparing的，我今天改了一下让他支持Executing和Preparing，大概有5-6个地方需要修改

**Comment by yugijiudai** [comment]
@kookob filter那里我看了下，好像就做了个判非空，如果是空他是没做任何处理的，窗口也没消失，现在我暂时是当空的时候让他窗口隐藏掉，并且把里面的数据清空，下次再打开窗口就不会有东西了

**Comment by kookob** [comment]
@yugijiudai 过滤设置问题修复了。
mybatis的哪个版本输出是Executing的？还没见过。这个有需要倒是可以做成配置的。
然后那个黄色背景我没动，看了下，是因为非正常日志去还原，出错的颜色，正常日志用Restore Sql from Selection功能背景颜色应该不刺眼。
你有clone下载，可以根据自己喜好修改。

**Comment by yugijiudai** [comment]
@kookob 我用的是3.0.2,他输出就是executing

**Comment by kookob** [comment]
@yugijiudai 刚查了下，那是最早期的mybatis版本，应该是从ibatis那边遗留过来的，2010年的。
之前想做成ibatis和mybatis都兼容的插件，后面发现两者输出还是挺多差异，而且ibatis用的人也少，就砍掉了。
我这插件在你的3.0.2上面能输出正常吗？

**Comment by yugijiudai** [comment]
@kookob 不能，我修改了一下插件的代码才行
