### ISSUE TITLE
要是可以自定义sql开头关键字就好了

### ISSUE THREAD

**Issue by Houtx** [kookob/mybatis-log-plugin#21]
Executing: update SYS_LOG SET.....
Parameters: ccbc79b43ac44a.....
如果可是设置 Executing、Parameters这两个关键字就很好用了

**Comment by kookob** [comment]
@Houtx 这个是可以实现的，你那边是什么场景下用会到？mybatis的输出关键字默认都是固定的。

**Comment by Houtx** [comment]
公司有个老项目输出 
Executing: select * from tablename where id=.......
Parameters:123
如果做成可配置开头关键字，就很方便了

**Comment by kookob** [comment]
@Houtx ibatis的？如果是ibatis的除了开头关键字不一样之后，后面的参数格式也不兼容，之前最早的另一个插件就是想做成兼容mybatis和ibatis的，后面发现差别还蛮大，才重新开发了这个mybatis插件。
你可以再完整对比下所有的输出日志，比如参数多一些的，参数带()的，参数带换行，逗号，各种各样格式的。

**Comment by kookob** [comment]
无回复关闭

**Comment by kobekebike** [comment]
我也是碰到了这个问题，Executing开头，然后发现用不了

**Comment by kookob** [comment]
@kobekebike 新版已经改成可配置，应该有更新吧
