### ISSUE TITLE
SQL来源只能是控制台输出吗

### ISSUE THREAD

**Issue by GreedyPirate** [kookob/mybatis-log-plugin#22]
首先很喜欢作者的这个插件，本地调试很方便，但是我更多的痛点问题是把项目发布到服务器上，sql都在日志里，作者能否提供一个输入框让我直接粘贴进来？

最后先给个star，持续关注下

**Comment by kookob** [comment]
@GreedyPirate 谢谢支持，这个已经考虑到了。
你随便新建一个文本文件或什么文件，就可以粘贴日志，然后右键`Restore Sql from Selection`，就可以达到目的。
（PS: 支持全选解析）

**Comment by GreedyPirate** [comment]
@kookob 原来如此，谢谢了
