### ISSUE TITLE
使用logback 只打印sql，没拼接参数怎么弄呢

### ISSUE THREAD

**Issue by yangzaiDL** [kookob/mybatis-log-plugin#23]
![image](https://user-images.githubusercontent.com/19410495/54119699-ec97c880-4430-11e9-8373-03fa27ad60f2.png)
![image](https://user-images.githubusercontent.com/19410495/54119764-13ee9580-4431-11e9-988f-9d2adc2388e9.png)
![Uploading image.png…]()

logback.xml文件还需要怎么配置吗

**Comment by kookob** [comment]
先把pattern改成这样试下。
<pattern>%date [%level] [%thread] %logger{80} [%file : %line] %msg%n</pattern>
如果可以，你再按你的实际打印改下格式，后面的 %msg%n 留着

**Comment by kookob** [comment]
html标签被github过滤掉了
`<pattern>%date [%level] [%thread] %logger{80} [%file : %line] %msg%n</pattern>`

**Comment by kookob** [comment]
无回复关闭
