### ISSUE TITLE
日期类型参数，输出后的sql无法执行，oracle数据库

### ISSUE THREAD

**Issue by panhb** [kookob/mybatis-log-plugin#24]
生成的sql语句  截取部分
AND ts.order_date >= '2019-03-10 00:00:00.0' 
AND ts.order_date < '2019-04-10 23:59:59.0'

执行报错
ORA-01861: literal does not match format string

转换后可执行
AND ts.order_date >= to_date('2019-03-10 00:00:00' , 'yyyy-mm-dd hh24:mi:ss') 
AND ts.order_date <  to_date('2019-04-10 23:59:59' , 'yyyy-mm-dd hh24:mi:ss') 

oracle版本
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production

**Comment by kookob** [comment]
最好能帮忙提供Preparing和Parameters语句

**Comment by panhb** [comment]
==>  Preparing: select O.* from TSALES_ORDER O WHERE O.VALID='T' AND O.ORDER_DATE >= ? AND O.ORDER_DATE <= ? 
==> Parameters: 2019-03-11 00:00:00.0(Timestamp), 2019-04-10 23:59:59.0(Timestamp)

转换后输出sql：
select O.*
 FROM TSALES_ORDER O
 WHERE O.VALID='T' AND O.ORDER_DATE >= '2019-03-11 00:00:00.0' AND O.ORDER_DATE <= '2019-04-10 23:59:59.0';

执行报错信息：
> ORA-01861: literal does not match format string

**Comment by kookob** [comment]
@panhb 这是oracle执行时需要指定日期格式，要用to_date转换下。
mybatis日志输出没包含这东西，就没办法自动转换出来，需要自己手工添加了。
