### ISSUE TITLE
sql log 控制台遮挡database console 输出

### ISSUE THREAD

**Issue by zl7261** [kookob/mybatis-log-plugin#26]
sql log的控制台窗口的优先级比自带的database console优先级更高;

1.ctrl+shift+alt+o 呼出mybatis sql log console
2.输出解析的sql
3.idea db插件执行sql,explain
4.explain结果显示在database console中,但是被sql log console遮挡住

**Comment by kookob** [comment]
@zl7261 有截图吗？没用过db插件，插件全名是啥？

**Comment by zl7261** [comment]
> @zl7261 有截图吗？没用过db插件，插件全名是啥？

![问题](https://user-images.githubusercontent.com/27967791/58676020-5f0daa00-8389-11e9-906d-5798155a71af.gif)

详见GIF图,IntelliJ 自带的db插件

**Comment by kookob** [comment]
@zl7261 你好，看了下图片，是没有问题的！
你第二次执行右键点击的是"Explain Plan", 所以显示的结果是执行计划，在下面的Plan标签左边还有个查询结果，你可以切过去看，跟mybatis log plugin插件互相没有影响。

**Comment by kookob** [comment]
@zl7261 或者你是想说Explain Plan窗口没有像Execute那样主动跳出来吗？
这个跟插件也没有关系，我试了把log插件关了，切到其他tab，执行Explain Plan都是不会跳出来的。
这个估计是idea默认的行为，可以找下是否可以设置弹出。

**Comment by zl7261** [comment]
> @zl7261 或者你是想说Explain Plan窗口没有像Execute那样主动跳出来吗？
> 这个跟插件也没有关系，我试了把log插件关了，切到其他tab，执行Explain Plan都是不会跳出来的。
> 这个估计是idea默认的行为，可以找下是否可以设置弹出。

好的,那应该跟这个插件没关系了,应该是IDEA的行为了.
