### ISSUE TITLE
现在部分log打印出来的日志不是preparing开头，而是Executing开头

### ISSUE THREAD

**Issue by kobekebike** [kookob/mybatis-log-plugin#27]
preparing和executing应该都支持才好。

**Comment by kookob** [comment]
@kobekebike 新版本？

**Comment by kobekebike** [comment]
mybatis3.0旧版本就是executing开头，升级之后才是preparing开头。

**Comment by kookob** [comment]
@kobekebike 如果能完整的粘几句示例，我这边看下，可能不只是executing不一样。
如果其他参数能兼容，到时候新版本做个支持。

**Comment by kobekebike** [comment]
`Executing: select * from app_step_export_file where step_id=? 
[22:28:47:647] [DEBUG] - org.apache.ibatis.logging.slf4j.Slf4jImpl.debug(Slf4jImpl.java:28) - ==> Parameters: 19(Long)
[22:28:47:650] [DEBUG] - org.apache.ibatis.logging.slf4j.Slf4jImpl.debug(Slf4jImpl.java:28) - ==>  Executing: select * from app_step_import_file where step_id=? 
[22:28:47:651] [DEBUG] - org.apache.ibatis.logging.slf4j.Slf4jImpl.debug(Slf4jImpl.java:28) - ==> Parameters: 19(Long)`

maven 应用jar包版本
`<mybatis.version>3.0.6</mybatis.version>
        <mybatis-spring.version>1.0.2</mybatis-spring.version>`
这两个jar包升级之后就可以preparing开头了。
这个日志输出就是没有升级版本的。

**Comment by kookob** [comment]
@kobekebike 好的，mybatis旧版本输出格式我已经做了兼容，然后插件新版本已经提交到仓库，过两天审核通过就可以下载更新了。

**Comment by kookob** [comment]
@kobekebike 已经发布，可以更新。

**Comment by kobekebike** [comment]
好的

**Comment by Houtx** [comment]
我用的mybatis-3.1 源码里确实输出executing,然后我fork了一下, 我自己改的, 全局替换这两个单词就行了. 暂未发现bug.
![image](https://user-images.githubusercontent.com/17922172/62920385-31f16500-bdd8-11e9-87d5-22cc852dad88.png)

**Comment by kookob** [comment]
@Houtx 好的，我新版本已经把这个前缀做成可配置了，并且对代码做了一些优化。
目前版本不影响使用，可以不用更新。

**Comment by Houtx** [comment]
@kookob 没看到有新版本啊... 项目首页还是说必须要有Preparing.   在哪里配置啊

**Comment by kookob** [comment]
@Houtx 首页说明没更新过来。直接仓库搜索，或者通过链接下载：
https://plugins.jetbrains.com/plugin/10065-mybatis-log-plugin
你如果用自己编译的，可能检测不到新版本。

**Comment by Houtx** [comment]
@kookob 好的

**Comment by Houtx** [comment]
@kookob 最好把readme给改一下, 可能有人不知道已经添加了这个功能.

**Comment by kookob** [comment]
@Houtx OK
