### ISSUE TITLE
无法捕捉Terminal输出的日志

### ISSUE THREAD

**Issue by leejuen** [kookob/mybatis-log-plugin#29]
我配合远程调试时发现Terminal里打印的日志无法捕获，而且也没有选中右键菜单。能否增加这个功能？

**Comment by kookob** [comment]
@leejuen 方便的话，帮忙截个图看下。
远程调试和terminal的日志输出，使用频率还是比较少，而且核心的解析sql日志这功能，不仅限用窗口的右键菜单，只要你能复制出日志，随便新建个文本文件或能粘贴内容的窗口，然后选中都会有右键菜单。
插件的主要功能是还原想要的sql语句，方便开发调试。
到目前为止没什么场景是不能通过复制，粘贴，右键菜单解决的。
所以远程日志的处理，对插件的功能提升比较小，不打算增加哦，抱歉了。

**Comment by leejuen** [comment]
![image](https://user-images.githubusercontent.com/6769738/59395372-27a1f300-8db6-11e9-8b6e-8ed5702cabfc.png)
是的只是在Terminal界面里不会显示插件的右键菜单，不过复制到一个新的文本中再右键选择确实可以解决这个问题

**Comment by kookob** [comment]
嗯，后面有研究了一下Terminal窗口，然后试了几种办法，都没能把右键菜单加在Terminal上面，后面发现它也是idea里面的一个插件实现的。
然后比较合理的解释是(个人觉得)：插件与插件之间的功能应该是互相独立的，没办法互相影响，不然idea启动加载就乱了，所以数据过滤和菜单这块无法实现。
后面有空的话，我可能会增加个窗口，直接粘贴日志，然后还原语句。
