### ISSUE TITLE
支持与spring boot集成时能识别mybatis.typeAliasesPackage设置

### ISSUE THREAD

**Issue by shuaicj** [kookob/mybatis-log-plugin#33]
与sprint boot集成时，配置mybatis.typeAliasesPackage或mybatis.type-aliases-package能设置alias。但mapper xml中使用alias会标红显示错误，但代码实际是可以编译运行的。

**Comment by kookob** [comment]
@shuaicj 你这个问题是另一个插件的吗？我的这个插件没你说的这个功能，是不是提错地方了？

**Comment by kookob** [comment]
@shuaicj 你请求的那个Pull requests已经合并，下个版本有发布时，才会更新哦。

**Comment by kookob** [comment]
@shuaicj 捐赠已收到，非常感谢你的祝福和支持。

**Comment by shuaicj** [comment]
@kookob 应该是你插件的功能，我没有装其他mybatis插件。比如mapper xml中如果引用了一个type：
- 如果xml中写全称`type="shuaicj.example.mybatis.domain.User"`，这种显然没有问题。
- 如果xml中写别名`type="User"`，并在User类上加上`@Alias("User")`，这种也不会有问题。
- 如果xml中写别名`type="User"`，并在spring boot的配置application.yml中写上`mybatis.typeAliasesPackage: shuaicj.example.mybatis.domain`，这个是mybatis-spring-boot支持的配置，可以把指定包下面的类全部加上mybatis alias，参见[mybatis-spring-boot-starter](http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Configuration)。这种情况下代码是可以运行的，但打开xml时intellij会在`type="User"`下标红，表示找不到这个type。确定不是这个插件的功能？因为我关闭插件这里就不会标红。

**Comment by shuaicj** [comment]
具体可以试试我的demo [https://github.com/shuaicj/spring-boot-mybatis-example](https://github.com/shuaicj/spring-boot-mybatis-example)

**Comment by kookob** [comment]
@shuaicj 插件没这功能。为什么关闭插件就不会标红，这我也搞不清楚了。
标红是intellij默认检测级别的功能，你可以照着下图设置一下看看：
![image](https://user-images.githubusercontent.com/3116606/60227991-d3be0080-98c3-11e9-9062-43c2d578cf12.png)

**Comment by kookob** [comment]
![image](https://user-images.githubusercontent.com/3116606/60228177-6d85ad80-98c4-11e9-87a5-d24c4a18aa23.png)
我试了你说的配置，也没标红

**Comment by shuaicj** [comment]
我找到了在inspection里面有两个配置：
<img width="566" alt="Screen Shot 2019-06-27 at 10 27 58" src="https://user-images.githubusercontent.com/5753437/60228693-1385e780-98c6-11e9-9da2-234fe53e0d12.png">
这两个inspection只有开启你的插件的时候才会有。

第一个inspection检查mapper class中的方法，如果对应的xml中未配置，则标红（看最后那个findByAbc）：
<img width="709" alt="Screen Shot 2019-06-27 at 10 28 35" src="https://user-images.githubusercontent.com/5753437/60228771-58118300-98c6-11e9-90fe-01dc607615e6.png">

第二个inspection检查mapper xml中的各种设置等，比如我这里说的type，如果type错误或检测不到会标红：
<img width="501" alt="Screen Shot 2019-06-27 at 10 28 57" src="https://user-images.githubusercontent.com/5753437/60228814-7d9e8c80-98c6-11e9-8499-0852e4e830e1.png">

写全称的没问题：
<img width="596" alt="Screen Shot 2019-06-27 at 10 29 24" src="https://user-images.githubusercontent.com/5753437/60228833-9018c600-98c6-11e9-8cca-6ce079513202.png">

给User类加上Alias注解，再使用别名也没问题：
<img width="219" alt="Screen Shot 2019-06-27 at 10 35 09" src="https://user-images.githubusercontent.com/5753437/60228919-cc4c2680-98c6-11e9-81df-25422e6adc1f.png">
<img width="515" alt="Screen Shot 2019-06-27 at 10 35 20" src="https://user-images.githubusercontent.com/5753437/60228930-d5d58e80-98c6-11e9-8c2e-cf48082cda30.png">

我只有一个mybatis插件，用的是intellij社区版：
<img width="537" alt="Screen Shot 2019-06-27 at 10 37 41" src="https://user-images.githubusercontent.com/5753437/60229064-3795f880-98c7-11e9-8b6f-dacda5fd84ed.png">
<img width="642" alt="Screen Shot 2019-06-27 at 10 38 24" src="https://user-images.githubusercontent.com/5753437/60229073-411f6080-98c7-11e9-9a1d-fd58042607b0.png">

**Comment by shuaicj** [comment]
找到原因了，是另一个插件'Free MyBatis Plugin'，我的锅。。。

**Comment by kookob** [comment]
OK
