### ISSUE TITLE
无法自动识别sql

### ISSUE THREAD

**Issue by Gynwn** [kookob/mybatis-log-plugin#36]
项目启动或者debug，插件都识别不出sql。但手工进行转换可以。

**Comment by Gynwn** [comment]
idea版本2019.1
插件版本2.0.9

**Comment by Gynwn** [comment]
很奇怪，重启应用的使用，能够转换最后一段sql。但是手工停止再启动又识别不出来

**Comment by kookob** [comment]
@Gynwn 检查下过滤配置那边有没有内容？
