### ISSUE TITLE
idea 2019.1多线程打印sql缺失

### ISSUE THREAD

**Issue by z1153202** [kookob/mybatis-log-plugin#37]
如题idea 2019.1多线程情况下只打印控制台的第一个sql，插件版本2.0.9

**Comment by kookob** [comment]
@z1153202 控制台的输出日志帮忙粘一下，我这边参考下

**Comment by z1153202** [comment]
@kookob 


![17_43_10__08_19_2019](https://user-images.githubusercontent.com/26903262/63256169-99f8ed00-c2a9-11e9-8e2c-1d28c364e1fd.jpg)

**Comment by kookob** [comment]
@z1153202 插件只是解析控制台的内容，日志输出顺序如此，插件目前没办法实现解析。
针对需要解析的，你可以手工拷出来，然后自己调整下顺序，然后用"restore sql from text"那个窗口获取你要的sql。

**Comment by z1153202** [comment]
@kookob 
![18_45_02__08_19_2019](https://user-images.githubusercontent.com/26903262/63259642-8cdffc00-c2b1-11e9-9c6c-7c184782ddfa.jpg)
现在的情况是只解析了第一个sql，后面两个线程sale-performance-statis-1，sale-performance-statis-4没解析

如果用restore sql from text的话，不用换顺序就能解析。
![18_54_06__08_19_2019](https://user-images.githubusercontent.com/26903262/63260296-1643fe00-c2b3-11e9-970e-64bedc4049d4.jpg)

**Comment by kookob** [comment]
@z1153202 那是因为你这几条语句都没有参数的，所以from text能解析正常。
插件只能处理控制台输出的最近两行，所以多线程这种场景，没办法处理。
