### ISSUE TITLE
使用一段时间后会记IDEA CPU的使用率很高，并且一直降不下来

### ISSUE THREAD

**Issue by radcat1987** [kookob/mybatis-log-plugin#40]
使用一段时间后会记IDEA CPU的使用率很高，并且一直降不下来

**Comment by kookob** [comment]
@radcat1987 不启用插件的情况下，CPU使用率一直正常吗？插件只过滤日志输出，理论上不会太占CPU性能。

**Comment by radcat1987** [comment]
在plugins页面把插件禁用后，CPU是正常的
那会我查问题的看堆栈的时候我记得是一个Queue的一个什么方法

并且CPU高的这个问题，在应用（spring boot application）不启动的时候，也会出现

**Comment by kookob** [comment]
把一些平时用不上的插件禁用掉，idea64.exe.vmoptions 文件里面的内存配大一些。

**Comment by radcat1987** [comment]
我就是把我自己安装的插件都禁用掉，并且IDEA自带的插件我不用的也都禁用掉，才排查出来是这个插件导致的CPU使用率高这个问题的
我IDEA的的内存也挺大的了，感觉不像是内存的问题。。。

**Comment by kookob** [comment]
你的日志很多，一直狂打印么？那你可以在需要还原sql语句的时候再开启，默认是停止过滤的(不是禁用插件)

**Comment by radcat1987** [comment]
关键问题是，我应用不启动的时候，CPU也会高。。。

**Comment by kookob** [comment]
那更不可能是插件引起的，看你是什么版本的idea，还有相关的jdk版本，之前有个版本好像有这个bug，官方有修复了，你可以升级或修改成其他版本。
我目前的版本：2018.2.5

**Comment by radcat1987** [comment]
我用的是IDEA版本是 2019.2.3
应该不是IDEA和JDK的问题，因为相同的环境，我把插件禁用掉，就没再复现过。

**Comment by kookob** [comment]
没见其他用户反馈过，应该跟特定环境有关系，这问题我不好排查，这边我先Close了。
