### ISSUE TITLE
sql里正则表达式里有?，格式化会被替换成参数

### ISSUE THREAD

**Issue by ghostman-git** [kookob/mybatis-log-plugin#41]
sql里正则表达式里有?，格式化会被替换成参数

**Comment by kookob** [comment]
@ghostman-git 麻烦粘贴下原始日志示例

**Comment by ghostman-git** [comment]
@kookob  原始日志无法提供了，提供个sql吧。 SELECT
  *
FROM
  T_DEMO T
WHERE
  regexp_replace(T.PROJECT_BASED, '<\/?.+?\/?>', '') LIKE CONCAT('%', CONCAT(?, '%'))

**Comment by kookob** [comment]
@ghostman-git 感谢反馈，测试和研究几种类似你上面的语句情况，很遗憾，目前的插件机制很难解决。
mybatis自定义的sql语句形式不胜枚举，特殊符号各种充插，难以解析。
例如：
`select * from test 
where name = 'select * from aaa WHERE (name = ? AND type = ? AND value = ?)'  
and code = ? and type = ' ?, hello(String), 100(Integer)'  
and replace(type, '</?.+?/?>', '') LIKE CONCAT('%', CONCAT(?, '%'))`   

语句也算正常的语句，但是插件对这种形式实在无能为力，所以该问题无解。
好在这类语句解析错误对实际工作影响不大，所以该问题暂时搁置，以后如果有其他实现机制再考虑下能否解决，谢谢！
