### ISSUE TITLE
最新版关闭tab不能再次生成sql(即不会显示sql的tab)

### ISSUE THREAD

**Issue by pog2g** [kookob/mybatis-log-plugin#45]
# 1、idea版本：2019.3，软件版本:2.0.9
# 2、实现步骤:
* 1)生成sql,并出现tab
* 2)关闭tab,如下截图
![image](https://user-images.githubusercontent.com/48884933/70423043-bcf11c00-1aa7-11ea-9db6-039c9b670fd9.png)
* 3)再次生成sql,tab不会出现，除非重启idea

**Comment by kookob** [comment]
@pog2g 感谢反馈，已经修复，需要等待下个版本更新(v2.1.0)
PS：如果关闭上面红色箭头位置，重新按快捷键或Tools->Mybatis Log Plugin，也会重新出来。

**Comment by kookob** [comment]
@pog2g 2.1.0已发布仓库
