### ISSUE TITLE
本地启动第三个项目插件不生效

### ISSUE THREAD

**Issue by yangjiabincomcn** [kookob/mybatis-log-plugin#47]
是因为设定了,第三个项目需要是收费的相关东西吗?

**Comment by kookob** [comment]
@yangjiabincomcn 没有设定收费的控制。
看下第三个项目的输出日志格式是否正常规范，你可以先右键'restore sql from selection' 试下，或可以粘贴一段出来看下。

**Comment by yangjiabincomcn** [comment]
右键 restore sql from  selection 后
请问要怎么解决?

| |
y
|
|
yangjiabincomcn@163.com
|
签名由网易邮箱大师定制
在2019年12月22日 10:14，ob<notifications@github.com> 写道：

@yangjiabincomcn 没有设定收费的控制。
看下第三个项目的输出日志格式是否正常规范，你可以先右键'restore sql from selection' 试下，或可以粘贴一段出来看下。

**Comment by yangjiabincomcn** [comment]
> @yangjiabincomcn没有设置收费的控制。
> 看下第三个项目的输出日志格式是否正常规范，你可以先右键'从选择中恢复sql'试下，或者可以将某些片段出来看下。

 右键restore sql from selection'  会提示这个Can't restore sql from selection.

**Comment by kookob** [comment]
@yangjiabincomcn 把原始语句粘贴一下

**Comment by yangjiabincomcn** [comment]
插件正常执行的项目右键点这个 也会出现Can't restore sql from selection. 


| |
y
|
|
yangjiabincomcn@163.com
|
签名由网易邮箱大师定制
在2019年12月30日 17:46，ob<notifications@github.com> 写道：

@yangjiabincomcn 把原始语句粘贴一下

**Comment by yangjiabincomcn** [comment]
17:28:16.529 logback [http-nio-8181-exec-2] DEBUG c.m.c.w.d.i.I.queryAll_COUNT - ==>  Preparing: SELECT count(0) FROM md_game AS t WHERE 1 = 1 
  这条sql 右键就会出现 Can't restore sql from selection.


| |
y
|
|
yangjiabincomcn@163.com
|
签名由网易邮箱大师定制
在2019年12月30日 18:02，y<yangjiabincomcn@163.com> 写道：
插件正常执行的项目右键点这个 也会出现Can't restore sql from selection. 


| |
y
|
|
yangjiabincomcn@163.com
|
签名由网易邮箱大师定制
在2019年12月30日 17:46，ob<notifications@github.com> 写道：

@yangjiabincomcn 把原始语句粘贴一下

**Comment by kookob** [comment]
@yangjiabincomcn 解析的时候，必须要包含Preparing:和Parameters:两个句子，就算第二句是空参数，也要选中，这样插件才能正确识别。

**Comment by yangjiabincomcn** [comment]
已经找到问题, 是日志配置有误 ! 感谢作者! 并没有设置收费相关设定!
