### ISSUE TITLE
sql print twice

### ISSUE THREAD

**Issue by jeffxjh** [kookob/mybatis-log-plugin#48]
when i  execute one sql command,the plugin print sql twice
![20191227095538](https://user-images.githubusercontent.com/44387640/71496612-1c646f80-288f-11ea-9d91-12ae47566284.png)
![20191227095558](https://user-images.githubusercontent.com/44387640/71496613-1cfd0600-288f-11ea-8ee5-c2348115e108.png)

**Comment by kookob** [comment]
@jeffxjh Does that happen every sql log? have multi-threads?

**Comment by jeffxjh** [comment]
this project is demo. single threads. is springboot test  causing?

**Comment by kookob** [comment]
I think it causes by springboot test, the test may be output log twice in console different places
