### ISSUE TITLE
日志不生效,重启项目时突然生效

### ISSUE THREAD

**Issue by yijiemanong** [kookob/mybatis-log-plugin#49]
idea 2019.1.3
日志不生效,重启项目时突然生效
![插件](https://user-images.githubusercontent.com/43195187/71616402-0210f580-2bf1-11ea-80bd-9379dfbfb52b.gif)

**Comment by kookob** [comment]
@yijiemanong 这问题我不大好定位，发布了新版本2.1.0，有需要可以更新观察下。

**Comment by yijiemanong** [comment]
好的  谢谢

**Comment by zhulibin2012** [comment]
我也碰到这个问题,而且有时即使生效,也是部分sql会打印,其他的sql不打印,所以目前基本没怎么用

**Comment by kookob** [comment]
@zhulibin2012 需要提供原生的sql日志，才能分析过滤器是否有考虑不全的地方。
