### ISSUE TITLE
支持下idea的黑色主题啊，

### ISSUE THREAD

**Issue by ghostman-git** [kookob/mybatis-log-plugin#5]

**Comment by ghostman-git** [comment]
希望能适配idea黑色主题，

**Comment by kookob** [comment]
@ghostman-git 感谢提出，自己一直用经典主题，一直忽略了这个场景。
已经对颜色稍微做了调整，看起来更舒服一些，不过没做太多细化。
刚刚提交到仓库，一两天后应该就会审核通过，请关注下。

**Comment by ghostman-git** [comment]
挺好的，奈斯，就是感觉这黄色略晃眼
