### ISSUE TITLE
日志不打印是要配置什么嘛

### ISSUE THREAD

**Issue by V-Vincen** [kookob/mybatis-log-plugin#52]

**Comment by V-Vincen** [comment]
开启后日志不打印没有任何显示

**Comment by kookob** [comment]
控制台有正常输出吗?

**Comment by V-Vincen** [comment]
程序控制台有输出的 mybatis log插件控制台没有任何输出

**Comment by kookob** [comment]
输出原始语句麻烦粘贴看看，有敏感信息请删除。

**Comment by V-Vincen** [comment]
有了 我把mybatis配置的输出配置配上后 mybatis log插件控制台就有了 也就是说一定需要开启mybatis sql语句的配置 插件才会输出
