### ISSUE TITLE
没有识别到sql

### ISSUE THREAD

**Issue by Kyofin** [kookob/mybatis-log-plugin#53]
![image](https://user-images.githubusercontent.com/18548053/75940409-ee6f5d00-5ec7-11ea-9f70-f0fa6a74eb65.png)

**Comment by kookob** [comment]
应该是格式不兼容，中间多了一行日志？正常情况Preparing和Parameters是连续的。

**Comment by Kyofin** [comment]
问题已解决，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ob"<notifications@github.com&gt;; 
发送时间: 2020年3月5日(星期四) 下午2:13
收件人: "kookob/mybatis-log-plugin"<mybatis-log-plugin@noreply.github.com&gt;; 
抄送: "四度"<1040080742@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kookob/mybatis-log-plugin] 没有识别到sql (#53)




应该是格式不兼容，中间多了一行日志？正常情况Preparing和Parameters是连续的。
