### ISSUE TITLE
UUID is failed to substitute

### ISSUE THREAD

**Issue by dgergely** [kookob/mybatis-log-plugin#56]
When using UUID, the values are not resolved correctly:

Actual:
`... WHERE users.id = 'ab068046-268f-49e6-8f7a-03d11550dbda(UUID), DELETED' AND status <> error;
---This is an error sql!---`

Expected:
`... WHERE users.id = 'ab068046-268f-49e6-8f7a-03d11550dbda' AND status <> 'DELETED';`

The worst part is that all the values after a UUID gets messed up, and "error" is substituted instead of the next parameter.

DB: PostgreSQL 12

**Comment by kookob** [comment]
Yes, I didn't list all the types, and I will add UUID type to the next version.
Thank you

**Comment by w8y56f** [comment]
使用spring test进行单元测试时，发现重复打印sql（打印了2次）。但是如果通过http方式调用，正常打印1次。可以写个最简单的springboot测一下。使用的是2.1.1的插件，2.x的springboot。详细日志见附件
[issue_是markdown.log](https://github.com/kookob/mybatis-log-plugin/files/4402000/issue_.markdown.log)

**Comment by kookob** [comment]
@w8y56f 好的，过后我测试下

**Comment by kookob** [comment]
@dgergely 版本已经更新

**Comment by dgergely** [comment]
@kookob Even the simplest is not working:

```
Preparing: SELECT ?, ?
Parameters: 37850685-22b1-4630-9a1d-d9f44a8db1f7(UUID), 37850685-22b1-4630-9a1d-d9f44a8db1f7(UUID)
```

Gives me:
``` 
 SELECT 37850685-22b1-4630-9a1d-d9f44a8db1f7(UUID), 37850685-22b1-4630-9a1d-d9f44a8db1f7(UUID), error;
---This is an error sql!---
--  --------------------------------------------------------
```

Expected:
```
SELECT '37850685-22b1-4630-9a1d-d9f44a8db1f7', '37850685-22b1-4630-9a1d-d9f44a8db1f7'
```

**Comment by kookob** [comment]
which version?

**Comment by dgergely** [comment]
@kookob 
2020.4.1
This is the latest available for me.

**Comment by kookob** [comment]
OK, I will fix it next version. Thanks.

**Comment by dgergely** [comment]
Thanks!

**Comment by dgergely** [comment]
@kookob 
Now I have the same issue, but with OffsetDateTime. Can you just fallback to the value that I can actually see on the log as string? That was working long time ago.

```
Preparing: SELECT ?, ?
Parameters: 2020-04-23T12:58:34.088812Z(OffsetDateTime), 2020-04-23T13:58:34.088812Z(OffsetDateTime)
```

Gives me:
```
 SELECT 2020-04-23T12:58:34.088812Z(OffsetDateTime), 2020-04-23T13:58:34.088812Z(OffsetDateTime), error;
---This is an error sql!---
--  --------------------------------------------------------
```

Expected:
```
SELECT '2020-04-23T12:58:34.088812Z', '2020-04-23T13:58:34.088812Z'
```

So in general it would be much better to use the value on the log if the type is unknown: 
```
Preparing: SELECT ?, ?
Parameters: something(SomeType), somethingElse(SomeOtherType)
```

```
SELECT 'something', 'somethingElse'
```

**Comment by kookob** [comment]
Ha, I didn’t add the remaining three unused ones, I will update a new version add all the remaining type.

**Comment by kookob** [comment]
The new version was updated.

**Comment by dgergely** [comment]
@kookob 
It is better, but still has issues, could you please test the example I wrote?
This:
```
Preparing: SELECT ?, ?
Parameters: 2020-04-23T12:58:34.088812Z(OffsetDateTime), 2020-04-23T13:58:34.088812Z(OffsetDateTime)
```
now gives:
```
 SELECT '2020-04-23T12:58:34.088812Z', ', 2020-04-23T13:58:34.088812Z';
--  --------------------------------------------------------
```

As you see the second one contains a **comma and a space**, which is not needed.

Also as I mentioned the general fallback could be useful in situations where there the type is not known.

**Comment by kookob** [comment]
Sorry, It was my fault, I will fix it again.

**Comment by kookob** [comment]
The new version(2020.4.4) was updated.

**Comment by dgergely** [comment]
It looks to be working, thanks!
