### ISSUE TITLE
购买了激活不了插件是什么情况呢

### ISSUE THREAD

**Issue by wotoutengleha** [kookob/mybatis-log-plugin#58]
提示激活码无效

**Comment by kookob** [comment]
跟IDE的激活码不是同一个，如果你有注册账号，直接账号登录试下看。

**Comment by wotoutengleha** [comment]
账号登录也不行 下载了插件的激活码也不行，我的IDEA是破解版的 有关系吗

**Comment by kookob** [comment]
破解版的我没试过，可能会有影响，过后我看下能不能验证下。

**Comment by kookob** [comment]
@wotoutengleha 我这边做了下测试，破解版的确实有影响，激活不成功。
这下不好办了，我这边处理不了。

**Comment by wotoutengleha** [comment]
那只能用原来的免费版本了 IDEA太贵了

**Comment by kookob** [comment]
嗯，理解的，后续我思考下有没有其他的收费方案针对非正版用户，近期把业余时间花在另一款插件的开发上面了，比较费时。。
如果你有需要退款，可以把你的收款码发上来，我这边给你转回去，抱歉了。

**Comment by wotoutengleha** [comment]
不退了，谢谢楼主， 回来TB买个激活码去得了 不用破解版了

**Comment by kookob** [comment]
OK，TB激活码不确定是否能正常使用，可以跟店家先沟通下。

**Comment by kookob** [comment]
顺便跟你说下，官方有EAP和Beta的版本，是可以免费使用，不需要订阅的。
2020.1 Beta build 201.6668.13
Released: March 25, 2020  
No subscription required
这两种版本都可能存在一些bug，大部分是不影响日常使用，目前beta版本已经出来了。
给你提供下方案，你可以考虑下是否安装这种版本。

**Comment by kookob** [comment]
@wotoutengleha 
https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

**Comment by michaelwoo1** [comment]
> @wotoutengleha
> https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

我这边用的IDEA破解版的，买了你的插件激活不了，帮我退下款吧

**Comment by kookob** [comment]
@michaelwoo1 邮箱发我一下

**Comment by michaelwoo1** [comment]
190762953@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ob"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 下午2:08
收件人:&nbsp;"kookob/mybatis-log-plugin"<mybatis-log-plugin@noreply.github.com&gt;;
抄送:&nbsp;"吴建军"<190762953@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kookob/mybatis-log-plugin] 购买了激活不了插件是什么情况呢 (#58)





 
@michaelwoo1 邮箱发我一下

**Comment by kookob** [comment]
@michaelwoo1 查收下邮箱

**Comment by JarvisHu0107** [comment]
> @michaelwoo1 邮箱发我一下
我这边一样  破解版的没有办法激活这个插件
