### ISSUE TITLE
请问开源协议是什么？在公司仅个人使用付费是个人还是商业？

### ISSUE THREAD

**Issue by PetalQ** [kookob/mybatis-log-plugin#59]
如题

**Comment by kookob** [comment]
该插件目前没有许可，就是采用默认的许可方式。
当然，这东西防君子不防小人。
因为你这边问到了，我今天有认真思考了一下，过后我会在首页加上说明。
目前我的想法是这样：
旧版本因为一些兼容问题的存在，已经不维护了，最后更新的版本也有提交到仓库，是免费的，只兼容到idea(2019.3)。
旧版本，个人和公司都可以免费使用。
针对idea2020版本，我重新发布了新插件并开启了收费。
如果大家自己本地修改源码以兼容2020版本，也是能使用。
但是这种使用仅限个人，在公司里还是建议用收费版本。
最后就是希望(禁止)，源码修改后，请不要再发布仓库或共享出去。
上面是我的一些想法，后续有变动，以首页说明为准。
如果你有好的建议，也请帮忙提出来，谢谢。

**Comment by withyanni** [comment]
> 该插件目前没有许可，就是采用默认的许可方式。
   ---默认的协议是指？GPL？MIT？还是什么呢？

> 但是这种使用仅限个人，在公司里还是建议用收费版本。
  ---收费版本能否购买个人版？

> 最后就是希望(禁止)，源码修改后，请不要再发布仓库或共享出去。
   ---开源之后他人修改再让其闭源，没有这种协议，也不太合理。

**Comment by PetalQ** [comment]
@kookob 
>该插件目前没有许可，就是采用默认的许可方式。
---默认的协议是指？GPL？MIT？还是什么呢？

>但是这种使用仅限个人，在公司里还是建议用收费版本。
---收费版本能否购买个人版？

>最后就是希望(禁止)，源码修改后，请不要再发布仓库或共享出去。
---开源之后他人修改再让其闭源，没有这种协议，也不太合理。

最好把github地址贴在idea的插件说明里，不然都找不到地址。。。

**Comment by kookob** [comment]
@withyanni 
- 可以看下前面介绍：
https://help.github.com/cn/github/creating-cloning-and-archiving-repositories/licensing-a-repository
- 收费版本可以购买个人版
- 后续可以加上(正常通过插件官网页面那边有链接)

**Comment by kookob** [comment]
整理的一些内容：
https://github.com/kookob/mybatis-log-plugin/blob/master/ABOUT.md
