### ISSUE TITLE
当SQL有换行的时候会提示SQL错误

### ISSUE THREAD

**Issue by abcwt112** [kookob/mybatis-log-plugin#6]
[DEBUG][2018/04/09 17:38:04][http-nio-7001-exec-7] (BaseJdbcLogger.java:159) - ==>  Preparing: insert into sql_execute_fact ( hash_code, sql_scripts, sql_type, execute_time, result_size, created_at ) values ( ?, ?, ?, ?, ?, ? ) 
[DEBUG][2018/04/09 17:38:04][http-nio-7001-exec-7] (BaseJdbcLogger.java:159) - ==> Parameters: d26e232643e79e6dd00f73a3dc770684(String), H4sIAAAAAAAAAIWMywrCMBBFf+XuWiHgY+vHDDGMTcGZSDIx5u+rhSKC4PJezjmFbxwMpcqo3Cjz
RFplB1/QD+7rb7NFeg9jLx/q6PAH2/+snxxC0uCNWhmHwcEiU2efHYSCknrhlXwC15wEW+FlPTgb
ppzqHZe+ipLU4nkBWJrAG84AAAA=(String), 0(Integer), 62(Long), 442(Long), 2018-04-09 17:38:04.761(Timestamp)

![image](https://user-images.githubusercontent.com/11142863/38491208-ce9babb0-3c1d-11e8-8c1a-fcafedbbd267.png)

154  restore sql from selection  - ==>
insert into sql_execute_fact ( hash_code, sql_scripts, sql_type, execute_time, result_size, created_at ) values ( 'd26e232643e79e6dd00f73a3dc770684', H4sIAAAAAAAAAIWMywrCMBBFf+XuWiHgY+vHDDGMTcGZSDIx5u+rhSKC4PJezjmFbxwMpcqo3Cjz, error, error, error, error );
---This is an error sql!---

![image](https://user-images.githubusercontent.com/11142863/38491253-eda8e766-3c1d-11e8-8936-52820d4a6926.png)

谢谢 ^_^

**Comment by kookob** [comment]
@abcwt112 你好，有试过mybatis直接输出的会存在这问题吗？
手工选择的，我是按行解析，不适合去解析多行的场景。

**Comment by abcwt112** [comment]
@kookob 
自动记录和手动去解析一样，也会报错
![image](https://user-images.githubusercontent.com/11142863/38799278-a12d5e2a-4196-11e8-9edf-b50f78f16939.png)

**Comment by kookob** [comment]
@abcwt112 试了一下，没重现出来，看下你安装的是否最新版本？不是的话，帮忙升级一下再验证。
当前最新2.0.3

**Comment by abcwt112** [comment]
@kookob 
是2.0.3版本,这个问题就是有换行符,并且后续还有其他字段的时候会出现
https://github.com/abcwt112/mybatis_log_bug
请看这个项目吧,里面就1个测试用例,跑那个测试用例就行了,数据库什么的都搭好了,随便用

**Comment by kookob** [comment]
@abcwt112 谢谢你提供的示例工程，费心了。
这种场景确实比较常见，刚刚做了修复，已经上传到插件仓库，2.0.4版本。
审核需要一两天，请留意下，再做更新。

**Comment by abcwt112** [comment]
@kookob 
好的.谢谢
