### ISSUE TITLE
添加打印时间以及可以配置只显示方法名，不显示全限定名

### ISSUE THREAD

**Issue by PetalQ** [kookob/mybatis-log-plugin#61]
--  109  [com.ABC.someMethods] - ==>
select * from B;

如下
--  109 2020-4-11 09:40:34  [someMethods] - ==>
select * from B;

**Comment by kookob** [comment]
时间，正常的日志输出本身都会带的，如果没有输出时间，那就是日志的配置格式不友好，感觉不是很有必要。
显示全限定名的本意是为了方便定位原日志窗口的位置，为了美化一些显示，做成配置的话，意义不大，我的关注点是，**能获取到自己想要的完整sql，以及最少的性能浪费。**
所以上面建议暂时不会添加，还是谢谢你的建议。
