### ISSUE TITLE
无法识别SQL

### ISSUE THREAD

**Issue by afsfge** [kookob/mybatis-log-plugin#62]
![image](https://user-images.githubusercontent.com/17295616/79112079-5d39b300-7db0-11ea-947b-4b4412d1f0c7.png)

![image](https://user-images.githubusercontent.com/17295616/79112297-d2a58380-7db0-11ea-84ef-51a152319598.png)

![image](https://user-images.githubusercontent.com/17295616/79112135-76dafa80-7db0-11ea-88ed-38034a3a800a.png)

idea2020.1，插件版本2020.4.1

**Comment by kookob** [comment]
左边那个启动按钮没开。

**Comment by afsfge** [comment]
> 左边那个启动按钮没开。

还有这个步骤啊，文档里没注意到，谢啦

**Comment by kookob** [comment]
默认是开的，为了不影响性能，不用时可以关闭。:)
