### ISSUE TITLE
插件激活失败问题处理

### ISSUE THREAD

**Issue by kookob** [kookob/mybatis-log-plugin#63]
遇到插件激活失败的情况，请先看下是不是特(po)殊(jie)版本引起的，详情查看这里：
https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md
有任何问题请随时联系或回复，谢谢。
官方账号登录地址：
https://account.jetbrains.com/licenses

**Comment by null06** [comment]
特殊版本插件激活失败，验证码是新购买的

**Comment by kookob** [comment]
错误提示是什么？

**Comment by null06** [comment]
key is invaild

**Comment by kookob** [comment]
mac还是windows?

**Comment by null06** [comment]
mac

**Comment by kookob** [comment]
麻烦联系下我邮箱：kookob@gmail.com，我给发个版本测试下。

**Comment by kookob** [comment]
因为JB家对破解版的签名验证不通过，导致激活失败(正版的不会，所以没发现)。
**目前特殊版本已更新，大家可以再试一下。**
造成不便，请大家理解。

**Comment by kookob** [comment]
因为JB家对破解版的签名验证不通过，导致激活失败。
目前特殊版本已更新，你可以再试一下。
https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md
给你造成不便，请谅解。
谢谢。

null06 <notifications@github.com> 于2020年4月15日周三 上午11:29写道：

**Comment by achievejia** [comment]
特殊版本怎么安装呢？ 我也是mac，运行不起来呀

**Comment by kookob** [comment]
打开上面的链接，下载mybatis-log-special.jar包，然后
File->Plugins->打开设置窗口
![image](https://user-images.githubusercontent.com/3116606/79637589-5ac1c980-81b3-11ea-8e58-89cff1ca0918.png)
选择你下载jar包的路径，确定后重启下IDE就可以了。

**Comment by achievejia** [comment]
好的，谢谢，麻烦您了

**Comment by achievejia** [comment]
@kookob 
您好，在麻烦您一下，这个激活码怎么转换？我咋怎么试都不对

**Comment by kookob** [comment]
@achievejia 
不用转换啊，你邮箱里面收到的，或者jetbrains后台下载下来的就是可以直接用的。
Email和Order Ref也要填对哦。

**Comment by achievejia** [comment]
非常感谢，麻烦您了

**Comment by RainingNight** [comment]
已支付，激活码在哪看？？

**Comment by kookob** [comment]
邮箱对的话，可能邮件有延迟，有账号的话，登录官网也能看。
https://account.jetbrains.com/licenses

**Comment by RainingNight** [comment]
> 邮箱对的话，可能邮件有延迟，有账号的话，登录官网也能看。
> https://account.jetbrains.com/licenses

这个页面说我“No Available Licenses”，可能延迟吧，明天再看。

**Comment by kookob** [comment]
你是具体几点几分买的，我感觉你没买成功？

**Comment by RainingNight** [comment]
> 你是具体几点几分买的，我感觉你没买成功？
> 延迟一般也不会超过5分钟。

可以了，已激活成功！

**Comment by CZDouble** [comment]
特殊版本下载链接打不开怎么回事，第三方下载软件也下载不了，求助。。

**Comment by kookob** [comment]
@CZDouble 应该是你那边网络问题，github昨天挂掉一会儿，现在都已经恢复，我这边测试可以下载。
我弄了个firefox临时下载地址，你试下：
https://send.firefox.com/download/053f4b3306fab23b/#7FL1SQRollZwsAvhGPgVMQ

**Comment by CZDouble** [comment]
@kookob 多谢，已经成功下载并激活使用啦

**Comment by zhangxiao961016** [comment]
你好，特殊版本的插件地址访问不了呀，可以给个别的地址吗？想购买一个特殊版本的

**Comment by lidaoping1990** [comment]
兄弟啊我这个idea 2020的用不了你这个插件啊？一致报错MyBatis Log Plugin License Authorization Faile

**Comment by kookob** [comment]
IDE是pojie的吗？是的话需要用特殊版本激活哦。

**Comment by pengzhile** [comment]
**很抱歉特殊版本给作者带来困扰。**

特殊版其实可以试试这个码：[Jetbrains paid plugins activation code (via jetbrains-agent)](https://zhile.io/jetbrains-paid-plugins-license.html)

**Comment by kookob** [comment]
@pengzhile 有了这个就不用购买ide和插件了吗？

**Comment by pengzhile** [comment]
> @pengzhile 有了这个就不用购买ide和插件了吗？

理论上来说，是的。

![image](https://user-images.githubusercontent.com/343491/80666618-578dde00-8acf-11ea-9c72-a819f18dc093.png)

**Comment by pengzhile** [comment]
> @pengzhile 有了这个就不用购买ide和插件了吗？

要的要的，非常鼓励有能力的朋友支持正版。

**Comment by kookob** [comment]
照顾一部分用户，不错不错。
不过你在这边发，是公然砸场啊，哈哈

**Comment by kookob** [comment]
@pengzhile 现在支持2020了吗？

**Comment by pengzhile** [comment]
> 照顾一部分用户，不错不错。
> 不过你在这边发，是公然砸场啊，哈哈

删了删了。

**Comment by pengzhile** [comment]
> @pengzhile 现在支持2020了吗？

支持的很完美。

**Comment by kookob** [comment]
这就厉害了。

**Comment by kookob** [comment]
@pengzhile 大佬，激活不成功啊，下载不到jetbrain-agent.jar了。
还有我的Smart Jump插件，到现在才卖了一份，没有使用，都准备放弃维护，你这码就支持了，哈哈。

**Comment by pengzhile** [comment]
> @pengzhile 大佬，激活不成功啊，下载不到jetbrain-agent.jar了。
> 还有我的Smart Jump插件，到现在才卖了一份，没人使用，都准备放弃维护，你这码就支持了，哈哈。

magnet:?xt=urn:btih:4b6427fac588f9fd50e7676d2e4dad1c9da36415

**Comment by Huguowei** [comment]
> @pengzhile 大佬，激活不成功啊，下载不到jetbrain-agent.jar了。
> 还有我的Smart Jump插件，到现在才卖了一份，没人使用，都准备放弃维护，你这码就支持了，哈哈。

magnet:?xt=urn:btih:4b6427fac588f9fd50e7676d2e4dad1c9da36415

**Comment by kookob** [comment]
@Huguowei 收到，感谢，我只是验证下情况，确实如 @pengzhile 所说，很完美啊。
本来就没卖多少份，这下更惨了，哈哈哈，一会儿我会把这里的聊天记录都清理掉。
对购买IDE或插件有困难的用户，我都不反对大家使用pojie版。
不过，我最近是真心投入时间去开发新插件，后续如果没有一点回报的话，将来我可能就放弃开发插件了。
SmartJump到现在才卖1刀，哈哈，此路不好走。
毕竟投入的时间可以拿去尝试做点其他更有回报的事情吧。

**Comment by pengzhile** [comment]
> @Huguowei 收到，感谢，我只是验证下情况，确实如 @pengzhile 所说，很完美啊。
> 本来就没卖多少份，这下更惨了，哈哈哈，一会儿我会把这里的聊天记录都清理掉。
> 对购买IDE或插件有困难的用户，我都不反对大家使用pojie版。
> 不过，我最近是真心投入时间去开发新插件，后续如果没有一点回报的话，将来我可能就放弃开发插件了。
> SmartJump到现在才卖1刀，哈哈，此路不好走。
> 毕竟投入的时间可以拿去尝试做点其他更有回报的事情吧。

你插件的价格已经非常非常良心了，只是对国内用户来说IDEA可能还是偏贵吧。
对插件市场的这种情况属于agent的误伤，因为jetbrains采用了相同的验证机制。
就像你发现的问题一样，用特殊版的IDEA他反而用不了正版的码。

我觉得是不是可以考虑采用自己的验证呢？

**Comment by kookob** [comment]
嗯，IDE价格对国内用户确实有点难接受。
我插件目前定的价格是仓库允许的最低价，官方回复好像是说不能少于1的小数。可能官方也要分成，太低他们也赚不到。
验证机制相同，所以我目前有出了个本地验证的，校验机制也很弱，可以随便绕过。

因为插件价格不高，如果有用户愿意花时间去绕过授权避免花费这$1，我也没什么好说的，只希望用户不要共享出去，或伤害插件的其他销售就好。

采用自己的验证，需要自己开发支付，国内只能支付宝和微信，会把国外用户挡住。
但是我后续的插件更希望卖给国外用户，他们赚美刀不心疼这一两刀的，所以暂时先不花时间在这上面。目前支持购买的用户量还是不多。
---
突然想到了一点：
你这破解IDE的验证机制，确实把插件也误伤了，要防的话，我可以加一重简单的验证，避免被绕过。

**Comment by pengzhile** [comment]
> 嗯，IDE价格对国内用户确实有点难接受。
> 我插件目前定的价格是仓库允许的最低价，官方回复好像是说不能少于1的小数。可能官方也要分成，太低他们也赚不到。
> 验证机制相同，所以我目前有出了个本地验证的，校验机制也很弱，可以随便绕过。
> 
> 因为插件价格不高，如果有用户愿意花时间去绕过授权避免花费这$1，我也没什么好说的，只希望用户不要共享出去，或伤害插件的其他销售就好。
> 
> 采用自己的验证，需要自己开发支付，国内只能支付宝和微信，会把国外用户挡住。
> 但是我后续的插件更希望卖给国外用户，他们赚美刀不心疼这一两刀的，所以暂时先不花时间在这上面。目前支持购买的用户量还是不多。
> 
> 突然想到了一点：
> 你这破解IDE的验证机制，确实把插件也误伤了，要防的话，我可以加一重简单的验证，避免被绕过。

你可以试着防御一下，不过我持比较悲观的态度 :)

**Comment by kookob** [comment]
@pengzhile 
后续看一下吧，我敢说目前你这个agent是国内pojie用最多的一种方法了。
大佬能拉我进下你的QQ群么，了解一下行情，哈哈
