### ISSUE TITLE
我购买了,感觉比较麻烦,只是一个插件而已功能又不多,弄成收费的,感觉有点过了

### ISSUE THREAD

**Issue by zyqchina** [kookob/mybatis-log-plugin#64]
我不明白你为什么要收费,你倒不如贴一个GitHub网页上面有你的捐赠信息,这样会有很多人用了感觉好就来捐赠,现在都没有人用,即使购买了下次也不会在来使用,早晚都有人弄出来新的,开源肯定会有人给你捐赠的,现在反而不会有人在用了,只是提一下建议

**Comment by zyqchina** [comment]
弄成收费的反而国外人更加不愿意使用,国外人感觉好的话会给你捐赠的

**Comment by kookob** [comment]
我太缺钱是真的，而且非常非常的缺，混的不好。
如果不差钱，我也就不会把新版本设置成收费了，不差钱，应该就不会写代码了吧，更加不会为了兼容api，升级各个版本吧。
官方[marketplace](https://plugins.jetbrains.com/marketplace)从去年6月开通，说明市场上这个需求肯定是存在的，推出这个也是鼓励开发者开发出更多优秀的插件，并收取适当的费用（官方有分佣15%，用于插件市场发展）。
虽然免费以及开源的插件不会消失，但是优秀插件的收费在官方的支持下应该会是一个趋势吧。
这只是我的第一个插件，因为大改版升级变成了收费，我又另外开发了另一个收费插件(Smart Jump)，效果好的话，后续还会开发新插件，只为增加点额外收入(迫于生计)。
说下开通捐赠的情况吧：
前期的版本我是有在github首页加个捐赠收款码，除了一个好友第一笔捐了50，其他总的加起来不到200，详情可以[看这边](https://github.com/kookob/mybatis-log-plugin/wiki/%E6%8D%90%E8%B5%A0%E5%88%97%E8%A1%A8)，有一些漏掉没补充进去，因为偶尔可能有个几块钱，就没及时加了。
目前我的想法就是，开发好的插件，让更多的用户使用，以及能让更多的用户愿意为插件付费，让自己能有更多的额外收入。
如果你不理解，也是正常，没个人的生活不一样，而且我真的很缺钱！
其他话就不多说了，还是谢谢你的建议！

**Comment by zyqchina** [comment]
我认为人用的多反而很好的赚钱,比如你弄一个交流群,或者找几个志同道合的朋友一起维护对吧,但是这样会限制你的流量,反而适得其反,我这样说你懂吧,我是今天无意间看到你的插件感觉很实用,如果你开放我相信会有很多人都喜欢的,有流量就有钱,现在谁都缺钱,所以愿意花钱的很少,但是那些不愿意花钱的肯定愿意推广呀,然后你的交流群还可以分享其他的插件,给同僚推广,给自己推广,我认为这样是更好的

**Comment by kookob** [comment]
现在所有的插件，都不是开发过程中必须要装的，甚至IDE都不是必须的(比如用记事本也可以开发java项目)，我们装了这么多IDE，工具，插件，都只是为了提升开发效率。
生产效率，开发效率的提高是我们永远的追求。
弄成收费，肯定会有很多人不愿意使用了，每个IDE，插件对不同的人开发效率的提升也不一样，
有人愿意为自己提升效率节省时间而付费，因为他觉得节省的时间比IDE或插件的费用更值得。
而我开发的收费插件所要服务的就是这类用户。

你后面的建议很好，过后我是应该建个QQ群来提供用户的交流，谢谢！

**Comment by zyqchina** [comment]
对的,我明白你说的意思,如果是你,你愿意使用一个不知道顺不顺手的插件就收钱的吗,大多都是朋友推广或者博客推广然后才有你收钱的这一步,前提还是流量,流量越多哪怕人少但是也很多,知道你坚持不容易,问题大家都懂,做软件的初衷目的都是为了赚钱,而且我感觉你并不是特别缺钱的人,做软件肯定比其他行业挣得多,说这么多归根结底我是希望这个插件用的非常多的,这样就能得到推广,比如下次我写博客我一定把你这个给写进去,不管别人用不,因为我感觉他值得被推荐,你可以利用流量在其他的地方赚钱,在这里获取流量,我个人这样认为

**Comment by kookob** [comment]
嗯，我理解，付费之前肯定得先试下插件能不能用，好不好用。
你安装插件的时候，默认都有30天的试用期，这个你没注意到吗？
JetBrains家的所有收费IDE，都是可以免费试用30天，所有的插件也是这样的。
谢谢你愿意帮助推广，说到推广，这插件确实都是网友自发帮忙，我自己基本上没发过帖，后续可能得做个广告啥的。
因为我本人暂时没有什么博客，对流量变现啥的也了解不多，可能有流量后确实能在其他地方赚到钱，但是这方面我暂时没经验，目前我懂的，就是开发一些插件，然后通过官方marketplace来销售，可以省掉很多其他的工作。
精力比较有限，目前主要是抽空在开发新的收费插件上面。

**Comment by zyqchina** [comment]
我没有注意到试用30天,不好意思,个人建议,最后全权有你选择,哈哈哈

**Comment by kookob** [comment]
我还是得谢谢你，真心的！
听到不同的声音挺好，我现在主要的问题是插件的定价，我新开发的那插件，后续版本更新，支持的场景更多之后，价格我就会提上去了。
