### ISSUE TITLE
离线可以激活吗?

### ISSUE THREAD

**Issue by sabersword** [kookob/mybatis-log-plugin#65]
你好,我已购买了lisence,使用的是IDAE2020.1 pojie版, mybatis-log-special .
在线可以正常激活,但是内网离线的话会出现如下报错

MyBatis Log Plugin License Authorization Failed.
\------------------------------------------------
plugin.obroom.com
\------------------------------------------------
plugin.obroom.com
\------------------------------------------------

**Comment by kookob** [comment]
是的，这个需要在线请求下jetbrains接口，判断下授权信息。目前内网可能就没办法了，有点麻烦了。。

Yan Peiquan <notifications@github.com> 于2020年4月17日周五 下午3:01写道：

**Comment by kookob** [comment]
目前内网验证不了授权信息，有点麻烦。

**Comment by sabersword** [comment]
了解,这也是没办法的事情,谢谢

**Comment by kookob** [comment]
谢谢理解，特殊版本我能验证的，也只是调用下官方api验证权限（仅一次），如果没联网，pojie版本地目前真的无法验证，特殊版本就没有发布的必要了。
