### ISSUE TITLE
你好 能不能用微信支付或者支付宝的方式购买呢？

### ISSUE THREAD

**Issue by saiyzh** [kookob/mybatis-log-plugin#66]

**Comment by kookob** [comment]
可以的，你点到最后一步支付页面的时候，就可以选了。

**Comment by saiyzh** [comment]
我已经成功购买了 ，不过我是第一次购买，不知道怎么样去激活呢，我收到jb发的邮件了，我打开idea里面有几种
![image](https://user-images.githubusercontent.com/40679184/79817405-063b6b80-83b8-11ea-9a80-4019c4c6f8bc.png)

**Comment by saiyzh** [comment]
看到了 原来要注册登录帐号才可以

**Comment by kookob** [comment]
好吧，打了一堆文字还没发出去，就收到你的回复了，哈哈。
感谢支持！

**Comment by kookob** [comment]
是激活成功了？选中间那个用激活码也是可以的 (正版IDE的前提下)

**Comment by saiyzh** [comment]
知道了 原来我的是学习版 我看一下另一份文档吧

**Comment by kookob** [comment]
学习版估计也可以吧，有问题随时联系。

**Comment by saiyzh** [comment]
是指pj版哈哈~谢谢协助!

**Comment by saiyzh** [comment]
你好 好像我下了特殊版没有提示我去输入订单信息验证，直接就能用了？

**Comment by kookob** [comment]
激活码，邮箱啥的都没填？ 还是有你有填过一次？

**Comment by saiyzh** [comment]
我先是在plugins下了试用版，然后输入邮箱发现激活不了，然后点了试用30天，然后卸载了重新下载特别版，打开就没有提示说要激活了。不知道是不是要等30天试用过后再输入呢

**Comment by kookob** [comment]
如果安装了特殊版本，试用功能应该就失效了，正常是要重新激活的，如果没有提示激活，那可能是特别版有问题，帮忙提供下order_ref。

**Comment by saiyzh** [comment]
有邮箱吗 我私聊发给你吧

**Comment by kookob** [comment]
好的，kookob@gmail.com
