### ISSUE TITLE
2019.2.3 x64 idea 不兼容这些收费版本

### ISSUE THREAD

**Issue by stevenxyy** [kookob/mybatis-log-plugin#67]
此前, 一直用2.1.0,挺好, 还免费. 道一句迟来的感谢!
昨日更新至2.1.1, 发现不能用, ...
试了你发布的所有收费版本.., 都不能用...

升级收费可以, 关键不能用了............ 
idea2019.2.3 (大哥, 别让我升级idea啊, 2020版的插件一大堆不兼容)...(┬＿┬)

![image](https://user-images.githubusercontent.com/46052093/79939403-9a2d3600-8491-11ea-89d0-fc2ea68b849d.png)
点这里没反应

**Comment by kookob** [comment]
左边的`Rerun`按钮有开启吗？左边的按钮也截图看一下
