### ISSUE TITLE
插件按钮自动出来但是不点一下不会去解析sql

### ISSUE THREAD

**Issue by c332030** [kookob/mybatis-log-plugin#68]
之前免费版需要点一下才会出现这个按钮，现在收费版启动会自动出来，但是不点一下不会去解析日志的sql。

![image](https://user-images.githubusercontent.com/15310784/79962832-256ef180-84bb-11ea-9418-18d88a5ccc77.png)

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to C C
Subscription is active until March 25, 2021
For educational use only.
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, cat.kanbanapps.gradlekiller, com.github.holgerbrandl.pasteimages/, Lombook Plugin, MyBatisLog, org.intellij.gitee, com.github.platan.gradle-dependencies-formatter, com.wakatime.intellij.plugin, de.netnexus.camelcaseplugin, JRebelPlugin, cn.wuzhizhan.plugin.mybatis

**Comment by kookob** [comment]
是的，有没有更方便？

**Comment by c332030** [comment]
> 是的，有没有更方便？

老哥，得点一下才会有sql解析，不点一直是空的

**Comment by c332030** [comment]
> 是的，有没有更方便？

刚刚误提交了，现在问题补全了

**Comment by kookob** [comment]
每次都会这样吗？正常情况是不需要点击的

**Comment by c332030** [comment]
> 每次都会这样吗？正常情况是不需要点击的

每次都这样，需要点一下

**Comment by c332030** [comment]
> 每次都会这样吗？正常情况是不需要点击的

公司网络原因图片上传不了

**Comment by kookob** [comment]
这就奇怪了，每次控制正常输出日志，然后需要点击一下Mybatis Log，然后日志才开始自动过滤出来？是时间上有延迟吗？

**Comment by c332030** [comment]
> 这就奇怪了，每次控制正常输出日志，然后需要点击一下Mybatis Log，然后日志才开始自动过滤出来？是时间上有延迟吗？

没有。点一下后如果有新的日志，马上会解析出来，是我的版本原因还是别的？

**Comment by kookob** [comment]
是哪个版本，我看下能不能重现

**Comment by c332030** [comment]
2020.4.2
Add some tips.
Fix bug.

**Comment by c332030** [comment]
> 是哪个版本，我看下能不能重现

![image](https://user-images.githubusercontent.com/15310784/79965523-b3001080-84be-11ea-9b7a-b08ec679e5e9.png)

**Comment by kookob** [comment]
收到，我看下能否重现，应该跟版本没关系，可能是其他原因，需要排查一下。

**Comment by c332030** [comment]
项目刚启动，然后点开是空的
![image](https://user-images.githubusercontent.com/15310784/79965658-dfb42800-84be-11ea-83b6-5ac2d4d20916.png)
![image](https://user-images.githubusercontent.com/15310784/79965672-e5aa0900-84be-11ea-9645-4f0e34aeabb7.png)

**Comment by kookob** [comment]
没有mybatis log的输出，默认就是空的，你看下日志有
Preparing:和Parameters: 这类的日志吗？

**Comment by c332030** [comment]
> 没有mybatis log的输出，默认就是空的，你看下日志有
> Preparing:和Parameters: 这类的日志吗？

有的
![image](https://user-images.githubusercontent.com/15310784/79967448-6d911280-84c1-11ea-9c80-d66d7e1b8888.png)
![image](https://user-images.githubusercontent.com/15310784/79967472-7681e400-84c1-11ea-8a70-c5c175d78a1d.png)

**Comment by kookob** [comment]
你这个是单元测试吗，如果不是单元测试的数据，也会这样吗？

**Comment by kookob** [comment]
帮忙检查下左边的Filter里面是否有配置东西？(不大好重现)

**Comment by c332030** [comment]
> 帮忙检查下左边的Filter里面是否有配置东西？(不大好重现)

我点开如果有新日志会有的
![image](https://user-images.githubusercontent.com/15310784/80093955-fda18b80-8597-11ea-9772-be87a019ec9d.png)

**Comment by kookob** [comment]
然后隐藏后，又不正常了？确实有点奇怪。

**Comment by c332030** [comment]
> 然后隐藏后，又不正常了？确实有点奇怪。

不是，我的意思是第一次打开idea，如果没有点开就不会有，点开后哪怕隐藏也还是有的

**Comment by kookob** [comment]
我知道问题了，确定是个大问题，竟然没发现，谢谢指出，下个版本修复。

**Comment by c332030** [comment]
^-^

**Comment by kookob** [comment]
新版本刚刚发布通过了，你可以更新下，加了点新功能。

**Comment by c332030** [comment]
好的

**Comment by kookob** [comment]
我最新发布的版本2020.4.6，把这个修复又去掉了。
因为工具窗口的特性就是没点击，默认就是没有激活的。我4.5的版本默认启动激活，有些用户建议默认不激活，影响有点不好，所以4.6又给去掉了。
因为不激活的话，如果旧日志语句没有过滤，可以通过右键复制所有日志，“Restore Sql"还原出来。
如果你确实需要，你可以更新4.5的版本。

**Comment by c332030** [comment]
好的
