### ISSUE TITLE
MyBatis Log Plugin License Authorization Failed.

### ISSUE THREAD

**Issue by zhangchunxing** [kookob/mybatis-log-plugin#70]
![image](https://user-images.githubusercontent.com/24538357/80052610-a971b980-854d-11ea-9f9c-5fbcb82a698e.png)

idea 2020.1版本教育账户，无法激活吗？

**Comment by kookob** [comment]
你这样就已经是激活的，不能正常使用的话，重启一上IDE看下。

**Comment by zhangchunxing** [comment]
已经OK。重启一下，然后，在起始界面输入账户激活，直接continue即可

**Comment by kookob** [comment]
嗯，目前JB家还在优化授权需要重启这块，后续版本可能就不需要重启了，感谢支持！
