### ISSUE TITLE
特殊版本下载链接失效

### ISSUE THREAD

**Issue by YeChuanShun** [kookob/mybatis-log-plugin#72]
activation.md文件中的下载链接失效了，无法访问

**Comment by kookob** [comment]
有FQ吗？晚点我换个链接。

**Comment by XuShuaiLiu** [comment]
未购买前激活时选了30天试用   购买许可证后找不到重新激活的按钮  安装mybatis-log-special.jar后也没有Rerun按钮

**Comment by YeChuanShun** [comment]
> 有FQ吗？晚点我换个链接。

需要fq么，好吧，没有使用fq

**Comment by YeChuanShun** [comment]
> 有FQ吗？晚点我换个链接。

fq之后成功下载了，但是提示我许可过期什么鬼

**Comment by kookob** [comment]
@YeChuanShun 装完启用，然后重启下IDE，点击窗口左边的rerun激活下。
具体可以看下文档操作，有问题随时回复。

**Comment by YeChuanShun** [comment]
> @YeChuanShun 装完启用，然后重启下IDE，点击窗口左边的rerun激活下。
> 具体可以看下文档操作，有问题随时回复。

是的，就是这么操作的，然后提示我许可过期

**Comment by kookob** [comment]
@YeChuanShun 帮忙截图，我看下是IDE的提示还是哪边的提示？

**Comment by YeChuanShun** [comment]
> @YeChuanShun 帮忙截图，我看下是IDE的提示还是哪边的提示？

![1587704841(1)](https://user-images.githubusercontent.com/44352976/80176904-a1d51200-862c-11ea-8072-0b8dd24f2522.png)

**Comment by kookob** [comment]
@YeChuanShun 应该是激活码的问题，你检查下是不是复制错了？

**Comment by YeChuanShun** [comment]
> @YeChuanShun 应该是激活码的问题，你检查下是不是复制错了？

没有的，防止我复制错误，我特地用这个激活码重新激活了一次

**Comment by YeChuanShun** [comment]
> @YeChuanShun 帮忙截图，我看下是IDE的提示还是哪边的提示？

![1587705112(1)](https://user-images.githubusercontent.com/44352976/80177088-32abed80-862d-11ea-9a53-3c78abda0de9.png)

**Comment by kookob** [comment]
@YeChuanShun 那麻烦你把验证的那三个信息发我邮箱，我验证看下，kookob@gmail.com，过后我会删除掉。

**Comment by YeChuanShun** [comment]
> @YeChuanShun 那麻烦你把验证的那三个信息发我邮箱，我验证看下，[kookob@gmail.com](mailto:kookob@gmail.com)，过后我会删除掉。

已发送，请查看

**Comment by kookob** [comment]
@YeChuanShun 还没收到，奇怪。

**Comment by YeChuanShun** [comment]
> @YeChuanShun 还没收到，奇怪。

判定为垃圾邮件，被退了，我换个邮箱，重新试下

**Comment by kookob** [comment]
或者打个zip包应该就可以。

**Comment by YeChuanShun** [comment]
> 或者打个zip包应该就可以。

![1587706759(1)](https://user-images.githubusercontent.com/44352976/80178536-0a25f280-8631-11ea-8c8d-3bde8db9a050.png)
哭了

**Comment by kookob** [comment]
这么尴尬，你直接回复在这边吧，我看到就马上删除！

**Comment by YeChuanShun** [comment]
> 这么尴尬，你直接回复在这边吧，我看到就马上删除！

1106397798@qq.com
R3754815

**Comment by kookob** [comment]
还需要激活码

**Comment by YeChuanShun** [comment]
> 这么尴尬，你直接回复在这边吧，我看到就马上删除！

[jetbrains-agent-latest.zip](https://github.com/kookob/mybatis-log-plugin/files/4526862/jetbrains-agent-latest.zip)

**Comment by kookob** [comment]
你发错了哦，这个包不是插件的，这是pojie的包。

**Comment by YeChuanShun** [comment]
> 你发错了哦，这个包不是插件的，这是pojie的包。

是的呢，插件就是在你这下载的，fq后可以下载，之前没有fq

**Comment by YeChuanShun** [comment]
> 你发错了哦，这个包不是插件的，这是pojie的包。
这是插件的
[mybatis-log-special.zip](https://github.com/kookob/mybatis-log-plugin/files/4526956/mybatis-log-special.zip)

**Comment by kookob** [comment]
你上面那个激活码过期，可能是激活码复制错了。
所以需要你把激活码发过来一下，我这边验证下是不是过期的？

**Comment by kookob** [comment]
一大串的那个激活码

**Comment by YeChuanShun** [comment]
> 你上面那个激活码过期，可能是激活码复制错了。
> 所以需要你把激活码发过来一下，我这边验证下是不是过期的？

激活码在pojie包里面，所有我就发给你了

**Comment by kookob** [comment]
理解错我的意思了，你买我插件的时候，插件有个独立的激活码，JB会发到你邮件，或者登录JB账号后台可以看到。
那就是你填错激活码了。不是pojie的码哦。

**Comment by kookob** [comment]
https://account.jetbrains.com/licenses

**Comment by YeChuanShun** [comment]
> 理解错我的意思了，你买我插件的时候，插件有个独立的激活码，JB会发到你邮件，或者登录JB账号后台可以看到。
> 那就是你填错激活码了。不是pojie的码哦。

哦哦，明白了，我重试下

**Comment by YeChuanShun** [comment]
> 理解错我的意思了，你买我插件的时候，插件有个独立的激活码，JB会发到你邮件，或者登录JB账号后台可以看到。
> 那就是你填错激活码了。不是pojie的码哦。

解决了，麻烦你了，谢谢

**Comment by kookob** [comment]
好的，一会我把这issue删了
