### ISSUE TITLE
选了30天试用 无法再激活

### ISSUE THREAD

**Issue by XuShuaiLiu** [kookob/mybatis-log-plugin#73]
未购买前激活时选了30天试用 购买许可证后找不到重新激活的按钮 安装mybatis-log-special.jar后也没有Rerun按钮

**Comment by kookob** [comment]
你需要把仓库安装的版本卸载，然后再装特殊版本，不然会有冲突。
按钮在窗口的左边，文档那边有截图你看下。

**Comment by XuShuaiLiu** [comment]
卸载之后重装也没有
会不会是idea版本影响
现在用的的是2020.1

**Comment by kookob** [comment]
不会影响，在你settings->plugin 看下插件的状态是什么？

**Comment by kookob** [comment]
![image](https://user-images.githubusercontent.com/3116606/80177670-eeb9e800-862e-11ea-826f-db7a63c6fd4d.png)
还有一个，如果是被隐藏，在这里让它显示

**Comment by XuShuaiLiu** [comment]
现在找到了 开始是一直在这里找没看到有Rerun按钮![image](https://user-images.githubusercontent.com/41193826/80178014-df876a00-862f-11ea-96be-979f5e21aea2.png)

**Comment by XuShuaiLiu** [comment]
已经激活了

**Comment by kookob** [comment]
好的，是我没表述清楚！
