### ISSUE TITLE
大神，从什么途径可以购买这款插件？

### ISSUE THREAD

**Issue by LingweiZeng** [kookob/mybatis-log-plugin#75]
contain **Parameters:** line:
`MyBatis Log Test: DEBUG sql1 -  ==>  Preparing: select * from t_table where name = ?`

contain **Preparing:** line:
`MyBatis Log Test: DEBUG sql1 -  ==> Parameters: hello(String)`

**Comment by kookob** [comment]
这里：
https://plugins.jetbrains.com/plugin/13905-mybatis-log-plugin/pricing#edition=personal

**Comment by LingweiZeng** [comment]
不是说1美元一年吗?现在这价格着实有些贵。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ob"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午9:48
收件人:&nbsp;"kookob/mybatis-log-plugin"<mybatis-log-plugin@noreply.github.com&gt;;
抄送:&nbsp;"曾令维"<382425001@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kookob/mybatis-log-plugin] 大神，从什么途径可以购买这款插件？ (#75)





 
这里：
 https://plugins.jetbrains.com/plugin/13905-mybatis-log-plugin/pricing#edition=personal

**Comment by kookob** [comment]
目前就是一美元一年的，个人的你要选下personal。

**Comment by LingweiZeng** [comment]
感谢大神耐心的指导，本人英语较差，在购买的过程中遇到了还是遇到了一些问题。建议做一个中文的购买指导流程照顾一下和我一样英文较差的小伙伴。

**Comment by kookob** [comment]
收到，下次出个流程
