### ISSUE TITLE
Mapper文件与接口跳转图标

### ISSUE THREAD

**Issue by zhangchunxing** [kookob/mybatis-log-plugin#76]
![image](https://user-images.githubusercontent.com/24538357/80450334-e249ce00-8953-11ea-89fb-f1e6634759b8.png)
你好，大佬。我本地有装mybatis的其它插件他已经支持这个跳转功能导致，如图上所示，出现2个图标。这个给我造成一定困扰。请问有配置可以把这个图标关了吗？我只需要打印日志功能。

**Comment by kookob** [comment]
可以的，在Settings里面有个Navigate复选框取消就可以了。

**Comment by zhangchunxing** [comment]
没有找到。。。

**Comment by kookob** [comment]
![image](https://user-images.githubusercontent.com/3116606/80452940-eb3d9e00-8959-11ea-9b20-8e585d02005a.png)

**Comment by zhangchunxing** [comment]
6666，我以为是idea的settings。3Q

**Comment by kookob** [comment]
有些用户没装你那插件，可能会有需要，先留着这功能，都不需要，我随时可以移除掉。
