### ISSUE TITLE
IDE是pojie的吗？是的话需要用特殊版本激活哦。

### ISSUE THREAD

**Issue by zhangxiao961016** [kookob/mybatis-log-plugin#77]
IDE是pojie的吗？是的话需要用特殊版本激活哦。

_Originally posted by @kookob in https://github.com/kookob/mybatis-log-plugin/issues/63#issuecomment-620508211_

**Comment by kookob** [comment]
可以了是吗？

**Comment by zhangxiao961016** [comment]
特殊版本激活地址无法访问呀

**Comment by kookob** [comment]
离线机器？没网络吗？

**Comment by zhangxiao961016** [comment]
有的呀，科学上网也访问不到呀

**Comment by kookob** [comment]
你是jar下载不成功吗？弄了个百度盘，看下是否可以
链接: https://pan.baidu.com/s/1lx-NiNItqjJFy7DKb3ivjQ 提取码: ibec

**Comment by kookob** [comment]
还是已经下载成功，不能激活？

**Comment by zhangxiao961016** [comment]
下载不成功，那我试一下这个百度网盘，谢谢你！

**Comment by zhangxiao961016** [comment]
购买的话也是正常在JB公司上面购买嘛？

**Comment by kookob** [comment]
是的

**Comment by zhangxiao961016** [comment]
明白啦，十分感谢！
