### ISSUE TITLE
插件会自动弹出来

### ISSUE THREAD

**Issue by sy714573037** [kookob/mybatis-log-plugin#78]
兄歹，你的这个插件只要重启或者打开idea，就自己弹出来，能不能想办法搞一下？还有xml导航能默认关闭就更完美了。

**Comment by kookob** [comment]
收到，一会儿发个版本处理掉。
导航可能用的人不，默认取消。
然后idea启动弹出来，是因为有部分用户反应说没激活过滤是不生效的(IDE特性)，所以加了启动弹出。
我个人也是倾向不弹出，因为语句大部分时间是不需要用到，要用到，右键解析也可以弥补。

**Comment by kookob** [comment]
新版本2020.4.6已经更新审核通过发布了。
