### ISSUE TITLE
无法试用？

### ISSUE THREAD

**Issue by liutf** [kookob/mybatis-log-plugin#79]
![image](https://user-images.githubusercontent.com/14069370/80805394-7fbe2f80-8bea-11ea-8aec-7e0fc06468a5.png)

![image](https://user-images.githubusercontent.com/14069370/80805400-851b7a00-8bea-11ea-985b-ed2b9f4ed6cf.png)

**Comment by kookob** [comment]
可以试用的，你这应该是可以的，上面的提示，只是说没启用，点击左边的Rerun就可以了。

**Comment by liutf** [comment]
OK，确实是点下 `return` 按钮后可以了，  本来是都没找到这个return 按钮，如果在说明能有个截图就更加一目了然了。

**Comment by kookob** [comment]
嗯，后面再优化下，上面提示的两行文字好像不怎么起作用？
