### ISSUE TITLE
run/debug 工具条中的 插件图标无法移除

### ISSUE THREAD

**Issue by othorizon** [kookob/mybatis-log-plugin#8]
IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 10, 2018
macOS 10.13.4

![image](https://user-images.githubusercontent.com/10081954/39107693-740e0bdc-46f6-11e8-9b55-da8272193228.png)
![image](https://user-images.githubusercontent.com/10081954/39107703-8585a014-46f6-11e8-89e1-e73303fc6993.png)
插件的这个图标即使从设置里面删除掉，界面上还是存在，而且很明显，这个插件的图标兼容性是存在问题的，移动这个图标的位置会导致界面显示的异常。

**Comment by kookob** [comment]
@othorizon 谢谢反馈，尝试过几次处理这个问题，暂时找不到好的方法移除。
一个是当时插件实现方式可能不是最优的方式。
另一个这按钮基本上是不影响任何插件的功能。
暂时能想到的解决办法是，重新构造插件的实现方式，但是目前不打算花精力重新改造插件去解决这个问题，抱歉了。

如有人知道如何简单解决的，帮忙告知下，谢谢。

**Comment by kookob** [comment]
暂时关闭，以后有精力再尝试解决
