### ISSUE TITLE
关于插件若干问题

### ISSUE THREAD

**Issue by 1125068334** [kookob/mybatis-log-plugin#83]
1.插件在什么情况下生效？ 日志输出为debug下？
2.使用poj jar包安装后，settings-plugins 中显示 mybatis-log-plugin（special）是否正常？
3.使用pj jar包安装后没有提示输入验证信息，rerun也没有弹出框。那么pj jar包是否有用还是不用此jar包安装也可？
烦请回复，谢谢。

**Comment by kookob** [comment]
1.  插件是根据run/debug里面有mybatis 相关的日志进行过滤的。
2. 正常
3. rerun能正常生效就是已经可用，说明你通过某种方式生效了吧，应该就能正常用了。

**Comment by 1125068334** [comment]
我通过jet购买的插件，没有让我输入插件验证信息 我就有点迷惑了，晚上回去用正常安装试一下 再看

**Comment by kookob** [comment]
这么奇怪，那你sql日志有正常解析还原出来吗？

**Comment by lamb218** [comment]
我购买了插件，提示：
Authorization Success!
Click the Rerun button again to enable plugin.
当我点击Rerun时，再次弹出了激活框，让我重新激活，这是什么原因？

**Comment by kookob** [comment]
每次都这样吗？

**Comment by lamb218** [comment]
是的，每次都这样

**Comment by kookob** [comment]
agent和插件都是哪个版本？

**Comment by lamb218** [comment]
插件是：2020.5.1
agent：3.0.0
IDEA是：2020.1 （企业破解版）

**Comment by lamb218** [comment]
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to xxxxxx

Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1973M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: CheckStyle-IDEA, GenerateSerialVersionUID, GrepConsole, GsonFormat, Lombook Plugin, MyBatisLog, VisualVMLauncher, com.moxun.plugin.s2v, org.jetbrains.plugins.spotbugs, soapUI Plugin, nb-mind-map-idea, com.alibaba.p3c.smartfox, com.markskelton.one-dark-theme, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, MavenRunHelper, com.alibabacloud.intellij.toolkit-intellij, GradleDependenciesHelper, cn.yiiguxing.plugin.translate, com.ccnode.codegenerator.MyBatisCodeHelperPro

**Comment by kookob** [comment]
agent作者有说要对本插件特殊处理，让用户二选一，不给使用，你看能否咨询一下对方，我的验证没什么其他处理。只能再排查排查。

**Comment by lamb218** [comment]
悲催！2019版能使用，升级了还用不了。。。。:(

**Comment by kookob** [comment]
你插件是直接仓库下载的吗？还是github页面下载的，如果仓库下载的用不了，建议下载这个试下吧：
https://raw.githubusercontent.com/kookob/mybatis-log-plugin/master/dist/mybatis-log-special.jar

**Comment by lamb218** [comment]
是仓库下载的，你发我的我激活后提示如下
Authorization Success!
------------------------------------------------
但是我使用Restore sql 就出现下面提示
MyBatis Log Plugin License Authorization Failed.
------------------------------------------------

**Comment by kookob** [comment]
说明有些激活信息漏了。

**Comment by CarlosShao** [comment]
> 说明有些激活信息漏了。

我是从idea插件仓库下的这个日志插件, 在idea里面是激活成功了,但是我只要重启idea, 就会弹出插件的激活步骤, [然后一直都是激活失败
![image](https://user-images.githubusercontent.com/35945730/82290842-65ea5e00-99da-11ea-8a7f-04c7cc082e94.png)
![image](https://user-images.githubusercontent.com/35945730/82290957-a053fb00-99da-11ea-8068-e13aeafe37f7.png)

**Comment by kookob** [comment]
@CarlosShao 
如果是pojie版需要用特殊版本激活。

**Comment by CarlosShao** [comment]
> @CarlosShao
> 如果是pojie版需要用特殊版本激活。

我idea是pojie的, 但是我插件是官网正是购买的

**Comment by kookob** [comment]
@CarlosShao 嗯，我知道，pojie版的IDE，不能直接激活收费插件，你照着这个流程看下能不能解决：
https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

**Comment by CarlosShao** [comment]
> @CarlosShao 嗯，我知道，pojie版的IDE，不能直接激活收费插件，你照着这个流程看下能不能解决：
> https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

好的, 多谢

**Comment by CarlosShao** [comment]
> @CarlosShao 嗯，我知道，pojie版的IDE，不能直接激活收费插件，你照着这个流程看下能不能解决：
> https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

感谢, 问题解决

**Comment by kookob** [comment]
@lamb218 可以试下新的版本能否解决：
https://raw.githubusercontent.com/kookob/mybatis-log-plugin/master/dist/mybatis-log-special.jar

**Comment by lamb218** [comment]
@kookob 
使用新的jar，提示我license已经过期，知道什么原因吗？使用之前的mybatis-log-special.jar是可以的一直出现：MyBatis Log Plugin License Authorization Failed.

**Comment by kookob** [comment]
特殊版本的新版需要重新验证一下，你看那边有没有弹出授权框？
