### ISSUE TITLE
mac 2020  idea 安装了 插件，但是tools里找不到？？

### ISSUE THREAD

**Issue by LeagendaryHe** [kookob/mybatis-log-plugin#85]
mac 2020  idea 安装了 插件，但是tools里找不到？？
![截图1](https://user-images.githubusercontent.com/22810951/82031470-83fb4a00-96cc-11ea-8fda-3311dacea27f.jpg)
![截图2](https://user-images.githubusercontent.com/22810951/82031479-88276780-96cc-11ea-978c-3b3857e9ef79.jpg)

**Comment by kookob** [comment]
不需要在tools菜单里面找了，直接在下面工具窗口就可以看到。
