### ISSUE TITLE
2020-05-22更新，更新之后无法激活

### ISSUE THREAD

**Issue by Tomao2014** [kookob/mybatis-log-plugin#87]
## 今天（2020-5-22）更新之后，无法弹出激活窗口

点击插件左边的Rerun按钮，无弹出授权验证窗口，输出的是

`MyBatis Log Plugin License Authorization Failed.
The first installation requires a restart of the IDE.`

![image](https://user-images.githubusercontent.com/46468204/82624899-55bec280-9c16-11ea-95b7-34aa684db7e4.png)

我是购买用户，`order ref ` ： `R3811802`，购买之后，成功激活过，也使用过一端时间。今天更新插件之后，反而无法使用了，求解。IDEA，我也重启过了，甚至连电脑都重启了。

**Comment by kookob** [comment]
更新后，下面的提示是重启IDE。
你是从仓库直接更新的吗？
pojie的IDE，需要用特殊版本更新。
这个特殊版本为了兼容社区版和教育版的。更新后可能需要重新激活一下。

**Comment by Tomao2014** [comment]
原先是用从IDEA下载和更新的，也正常使用过一段时间

刚试了一下， github 的版本，正常了
