### ISSUE TITLE
Activication code: 插件的激活码 填什么？

### ISSUE THREAD

**Issue by huangze1008** [kookob/mybatis-log-plugin#88]
填邮件中附件中的License ID激活失败

购买订单号是R3859395

**Comment by kookob** [comment]
需要激活码和邮箱一起。有提示什么错吗？

**Comment by huangze1008** [comment]
huang_zsh@126.com
 
发件人： ob
发送时间： 2020-05-22 11:06
收件人： kookob/mybatis-log-plugin
抄送： huangze; Author
主题： Re: [kookob/mybatis-log-plugin] Activication code: 插件的激活码 填什么？ (#88)
需要激活码和邮箱一起。有提示什么错吗？

**Comment by huangze1008** [comment]
key is invalid

**Comment by kookob** [comment]
你要填对应的激活码，登录官网后台可以看到：
https://account.jetbrains.com/licenses

**Comment by wq2022** [comment]
已经激活的，今天清理缓存后显示：MyBatis Log Plugin License Authorization Failed.
The first installation requires a restart of the IDE.
------------------------------------------------
点击Rerun 还是提示：MyBatis Log Plugin License Authorization Failed.
The first installation requires a restart of the IDE.
------------------------------------------------
无法使用，求解。

**Comment by SuMiaoALi** [comment]
我就想问问，特殊版本的都是channel激（po）活（解），只有激活码，哪有什么邮箱和订单号，你们是不让激（po）活（解）的人用呗？那出这个特殊版本有什么用没呢？脱裤子放*吗？

**Comment by kookob** [comment]
@SuMiaoALi 你有官网购买下单，就会有邮箱和激活码了。
