### ISSUE TITLE
5月22号，今天更新过软件，清理过缓存就无法使用了

### ISSUE THREAD

**Issue by wq2022** [kookob/mybatis-log-plugin#89]
已经激活的，今天清理缓存后显示：MyBatis Log Plugin License Authorization Failed.
The first installation requires a restart of the IDE.
点击Rerun 还是提示：MyBatis Log Plugin License Authorization Failed.
The first installation requires a restart of the IDE.
无法使用，求解。

**Comment by wq2022** [comment]
MyBatis Log是直接从idea的仓库下载的，idea的版本是IntelliJ IDEA 2020.1.1 (Ultimate Edition)

**Comment by kookob** [comment]
特殊版本不能升级仓库的版本哦。具体再看下这里，然后重新安装下特殊版本，抱歉了。
https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

**Comment by wq2022** [comment]
好的，已经可以了，谢谢
