### ISSUE TITLE
离线激活只能激活一次吗？现在这么也激活不了

### ISSUE THREAD

**Issue by Yelu97** [kookob/mybatis-log-plugin#90]
买的时候用激活码激活了一次，好像成功，过了几天好像又自动失效了，再次激活会报Key is invalid.

![Snipaste_2020-05-25_15-11-48](https://user-images.githubusercontent.com/24434195/82787946-13a5b300-9e9a-11ea-871b-dccb3313eeb7.png)
再问下，还有什么激活方式吗？（破解版）

**Comment by kookob** [comment]
看下这边：
https://github.com/kookob/mybatis-log-plugin/blob/master/activation.md

**Comment by Yelu97** [comment]
![Snipaste_2020-05-25_15-24-54](https://user-images.githubusercontent.com/24434195/82788894-e9ed8b80-9e9b-11ea-86d1-b1b37b288c15.png)

**Comment by kookob** [comment]
R开头的7位数字。邮箱 或 https://account.jetbrains.com/licenses 这里能查到

**Comment by Yelu97** [comment]
ok了，3Q
