### ISSUE TITLE
正版idea无法激活license

### ISSUE THREAD

**Issue by PetalQ** [kookob/mybatis-log-plugin#91]
5.3版本，从插件市场下的。
rerun 提示
MyBatis Log Plugin License Authorization Failed.
The first installation requires a restart of the IDE.
插件里也显示purchased，license明年到期。
传不了图。

**Comment by kookob** [comment]
The first installation requires a restart of the IDE.
首次安装授权后要重启下IDE

**Comment by PetalQ** [comment]
> The first installation requires a restart of the IDE.
> 首次安装授权后要重启下IDE

已多次重启，不生效 @kookob

**Comment by kookob** [comment]
用账号登录还是激活码的？

**Comment by PetalQ** [comment]
> 用账号登录还是激活码的？

账号激活和离线激活码激活，两种方式都试了，都不行 @kookob

**Comment by kookob** [comment]
IDE正版是Ultimate的正版吗？

**Comment by PetalQ** [comment]
> IDE正版是Ultimate的正版吗？

IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to XXX

Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: debugger.watches.in.variables=false, debugger.showTypes=false
Non-Bundled Plugins: zielu.gittoolbox, Lombook Plugin, MyBatisLog, com.godwin.json.parser, com.intellij.zh, com.codota.csp.intellij, com.zhaow.restful.toolkit, izhangzhihao.rainbow.brackets, cn.wuzhizhan.plugin.mybatis
@kookob

**Comment by kookob** [comment]
方便远程的话，加一下我QQ：151243466

**Comment by withyanni** [comment]
> 方便远程的话，加一下我QQ：151243466

公司电脑，远程不了。需要什么信息我可以文字发下。
@kookob

**Comment by kookob** [comment]
好的，目前是插件安装，然后是enable状态，然后启动时提示：
MyBatis Log Plugin License Authorization Failed.
点左边Rerun也一直这样，对吗？
把Help->Register的那个授权界面截图发一下。

直接截图，然后在issue, ctrl+v就可以粘贴了。

**Comment by PetalQ** [comment]
公司限制在github传图，传不上来。
文字描述：

许可证授予 rockyanni.
订阅有效期至May 27,2021.
您有此版本的永久回退许可证。

下面就是按钮移除许可证和认证方式了
@kookob

**Comment by kookob** [comment]
还有下面插件的授权信息吗？显示什么？

**Comment by PetalQ** [comment]
> 还有下面插件的授权信息吗？显示什么？

加你QQ吧，拍给你。 @kookob

**Comment by kookob** [comment]
@withyanni 1 5 1 2 4 3 4 6 6
