### ISSUE TITLE
赶紧更新吧，IDEA提示更新好几天了，总是提示更新

### ISSUE THREAD

**Issue by hopana** [kookob/mybatis-log-plugin#92]

**Comment by kookob** [comment]
如果是特殊版本，更新下最新的特殊版本就不会提示了。

**Comment by hopana** [comment]
> 如果是特殊版本，更新下最新的特殊版本就不会提示了。

![image](https://user-images.githubusercontent.com/13976824/83241556-95188080-a1cd-11ea-9fa9-791d5494850c.png)
有提示啊，不信自己看，右下角还有弹窗呢

**Comment by kookob** [comment]
如果你之前是装仓库的版本，可以直接更新的。如果是特殊版本，需要用特殊版本更新。

**Comment by hopana** [comment]
仓库版感觉随时可能河蟹，算了，装这个吧

**Comment by kookob** [comment]
@hopana 为啥会和谐？ide正版的话，肯定没问题！
