### ISSUE TITLE
特殊版可以帮忙放个云盘啥的吗，这个地址下载很慢。

### ISSUE THREAD

**Issue by liuminda** [kookob/mybatis-log-plugin#93]

**Comment by kookob** [comment]
https://send.firefox.com/download/af696d61f3fcef32/#6utvFiMcy-grZSQ6fVjDGQ

**Comment by liuminda** [comment]
> https://send.firefox.com/download/af696d61f3fcef32/#6utvFiMcy-grZSQ6fVjDGQ

哇，好速度，谢谢了。

**Comment by RongXiong2016** [comment]
> https://send.firefox.com/download/af696d61f3fcef32/#6utvFiMcy-grZSQ6fVjDGQ

连接已失效

**Comment by kookob** [comment]
@RongXiong2016 已经不支持了

**Comment by kookob** [comment]
@RongXiong2016 是啊，你是什么时候买的？

**Comment by RongXiong2016** [comment]
> @RongXiong2016 是啊，你是什么时候买的？

就在刚刚，

**Comment by kookob** [comment]
那就尴尬了，没看到提示么，你给我邮箱发个邮件吧，我发个东西给你。

**Comment by RongXiong2016** [comment]
> 那就尴尬了，没看到提示么，你给我邮箱发个邮件吧，我发个东西给你。
 邮件已发请查收~

**Comment by RongXiong2016** [comment]
@kookob
