### ISSUE TITLE
order ref format error

### ISSUE THREAD

**Issue by KaapoMarcus** [kookob/mybatis-log-plugin#96]
买了一年 之前按照介绍激活了，前天电脑系统重装了，我的order ref 应该怎么填 ？一直提示格式不对

**Comment by kookob** [comment]
R开头加7位数字，https://account.jetbrains.com/licenses
官网后台可以获取。

**Comment by KaapoMarcus** [comment]
> R开头加7位数字，https://account.jetbrains.com/licenses
> 官网后台可以获取。

已经激活 谢谢了  这插件是真香
