### ISSUE TITLE
无法激活

### ISSUE THREAD

**Issue by dinglixin** [kookob/mybatis-log-plugin#98]
我是用的是正版的idea，在plugins安装了mybatis log plugins，点击链接支付，然后一直显示没有权限，重启idea任何变化直接进来。请问到底该怎么激活呢？
MyBatis Log Plugin License Authorization Failed.
------------------------------------------------

**Comment by kookob** [comment]
正版IDE哪个版本？安装后检查下help->Register...菜单下面的插件授权框是否授权了。
别外需要重启下IDE的（检查下plugins里面是否启用)
