### ISSUE TITLE
idea账号激活失败

### ISSUE THREAD

**Issue by Dare-Huang** [kookob/mybatis-log-plugin#99]
您好：
        请问一下，我用idea账号直接登录提示No suitable licenses associated with account XXX，是什么原因？

**Comment by kookob** [comment]
这个是JB家报的，IDE是正版的吗？

**Comment by Dare-Huang** [comment]
是的，官网上下载的

**Comment by kookob** [comment]
IDE哪个版本的？

**Comment by Dare-Huang** [comment]
> 这个是JB家报的，IDE是正版的吗？

**Comment by Dare-Huang** [comment]
> IDE哪个版本的？
官网上下载的最新版本

**Comment by Dare-Huang** [comment]
Ide是官网上下载的最新版

**Comment by kookob** [comment]
IDE的激活账号是插件的购买账号吗？

**Comment by Dare-Huang** [comment]
> IDE的激活账号是插件的购买账号吗？

是说要用ide那个账号去购买一次插件吗，不是说可以直接登录激活

**Comment by kookob** [comment]
如果是正常IDE账号激活的话，插件应该跟IDE的账号是一起的，主要是看你IDE的激活方式是不是官方购买的授权信息。

**Comment by Dare-Huang** [comment]
> 如果是正常IDE账号激活的话，插件应该跟IDE的账号是一起的，主要是看你IDE的激活方式是不是官方购买的授权信息。

是教育邮箱申请的账号

**Comment by kookob** [comment]
那你插件下单的也是教育邮箱吗？

**Comment by Dare-Huang** [comment]
插件是在ide里面直接安装的，需要用教育邮箱再申请一次吗

**Comment by kookob** [comment]
插件新版目前是需要付费购买的哦，不是免费的，你可以先试用一个月

**Comment by Dare-Huang** [comment]
> 插件新版目前是需要付费购买的哦，不是免费的，你可以先试用一个月

可以用教育邮箱申请吗

**Comment by kookob** [comment]
本插件目前不支持教育邮箱免费哦，你还是学生吗？

**Comment by Dare-Huang** [comment]
> 本插件目前不支持教育邮箱免费哦，你还是学生吗？

好的
